// Code generated by internal/mapsgen — DO NOT EDIT.
// Re-run via `go generate ./...` from the repository root.

package qdf

import (
	"reflect"
	"slices"
	"unsafe"
)

// ----- map[string]string -----

func encodeMapStringString(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]string)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteString(v)
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteString(v)
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteString(v)
	}
	return nil
}

func decodeMapStringString(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]string)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, string](d, p, len(names))
		for _, k := range names {
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			m[k] = v
		}
		*(*map[string]string)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, string](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		v, err := d.ReadString()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[string]string)(p) = m
	return nil
}

// ----- map[string]bool -----

func encodeMapStringBool(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]bool)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteBool(v)
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteBool(v)
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteBool(v)
	}
	return nil
}

func decodeMapStringBool(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]bool)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, bool](d, p, len(names))
		for _, k := range names {
			v, err := d.ReadBool()
			if err != nil {
				return err
			}
			m[k] = v
		}
		*(*map[string]bool)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, bool](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		v, err := d.ReadBool()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[string]bool)(p) = m
	return nil
}

// ----- map[string]int8 -----

func encodeMapStringInt8(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]int8)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteInt(int64(v))
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteInt(int64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteInt(int64(v))
	}
	return nil
}

func decodeMapStringInt8(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]int8)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, int8](d, p, len(names))
		for _, k := range names {
			vWide, err := d.ReadInt()
			if err != nil {
				return err
			}
			v := int8(vWide)
			m[k] = v
		}
		*(*map[string]int8)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, int8](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		vWide, err := d.ReadInt()
		if err != nil {
			return err
		}
		v := int8(vWide)
		m[k] = v
	}
	*(*map[string]int8)(p) = m
	return nil
}

// ----- map[string]int16 -----

func encodeMapStringInt16(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]int16)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteInt(int64(v))
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteInt(int64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteInt(int64(v))
	}
	return nil
}

func decodeMapStringInt16(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]int16)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, int16](d, p, len(names))
		for _, k := range names {
			vWide, err := d.ReadInt()
			if err != nil {
				return err
			}
			v := int16(vWide)
			m[k] = v
		}
		*(*map[string]int16)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, int16](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		vWide, err := d.ReadInt()
		if err != nil {
			return err
		}
		v := int16(vWide)
		m[k] = v
	}
	*(*map[string]int16)(p) = m
	return nil
}

// ----- map[string]int32 -----

func encodeMapStringInt32(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]int32)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteInt(int64(v))
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteInt(int64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteInt(int64(v))
	}
	return nil
}

func decodeMapStringInt32(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]int32)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, int32](d, p, len(names))
		for _, k := range names {
			vWide, err := d.ReadInt()
			if err != nil {
				return err
			}
			v := int32(vWide)
			m[k] = v
		}
		*(*map[string]int32)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, int32](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		vWide, err := d.ReadInt()
		if err != nil {
			return err
		}
		v := int32(vWide)
		m[k] = v
	}
	*(*map[string]int32)(p) = m
	return nil
}

// ----- map[string]int -----

func encodeMapStringInt(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]int)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteInt(int64(v))
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteInt(int64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteInt(int64(v))
	}
	return nil
}

func decodeMapStringInt(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]int)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, int](d, p, len(names))
		for _, k := range names {
			vWide, err := d.ReadInt()
			if err != nil {
				return err
			}
			v := int(vWide)
			m[k] = v
		}
		*(*map[string]int)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, int](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		vWide, err := d.ReadInt()
		if err != nil {
			return err
		}
		v := int(vWide)
		m[k] = v
	}
	*(*map[string]int)(p) = m
	return nil
}

// ----- map[string]int64 -----

func encodeMapStringInt64(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]int64)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteInt(int64(v))
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteInt(int64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteInt(int64(v))
	}
	return nil
}

func decodeMapStringInt64(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]int64)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, int64](d, p, len(names))
		for _, k := range names {
			v, err := d.ReadInt()
			if err != nil {
				return err
			}
			m[k] = v
		}
		*(*map[string]int64)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, int64](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		v, err := d.ReadInt()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[string]int64)(p) = m
	return nil
}

// ----- map[string]uint8 -----

func encodeMapStringUint8(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]uint8)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteUint(uint64(v))
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteUint(uint64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteUint(uint64(v))
	}
	return nil
}

func decodeMapStringUint8(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]uint8)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, uint8](d, p, len(names))
		for _, k := range names {
			vWide, err := d.ReadUint()
			if err != nil {
				return err
			}
			v := uint8(vWide)
			m[k] = v
		}
		*(*map[string]uint8)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, uint8](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		vWide, err := d.ReadUint()
		if err != nil {
			return err
		}
		v := uint8(vWide)
		m[k] = v
	}
	*(*map[string]uint8)(p) = m
	return nil
}

// ----- map[string]uint16 -----

func encodeMapStringUint16(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]uint16)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteUint(uint64(v))
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteUint(uint64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteUint(uint64(v))
	}
	return nil
}

func decodeMapStringUint16(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]uint16)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, uint16](d, p, len(names))
		for _, k := range names {
			vWide, err := d.ReadUint()
			if err != nil {
				return err
			}
			v := uint16(vWide)
			m[k] = v
		}
		*(*map[string]uint16)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, uint16](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		vWide, err := d.ReadUint()
		if err != nil {
			return err
		}
		v := uint16(vWide)
		m[k] = v
	}
	*(*map[string]uint16)(p) = m
	return nil
}

// ----- map[string]uint32 -----

func encodeMapStringUint32(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]uint32)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteUint(uint64(v))
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteUint(uint64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteUint(uint64(v))
	}
	return nil
}

func decodeMapStringUint32(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]uint32)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, uint32](d, p, len(names))
		for _, k := range names {
			vWide, err := d.ReadUint()
			if err != nil {
				return err
			}
			v := uint32(vWide)
			m[k] = v
		}
		*(*map[string]uint32)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, uint32](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		vWide, err := d.ReadUint()
		if err != nil {
			return err
		}
		v := uint32(vWide)
		m[k] = v
	}
	*(*map[string]uint32)(p) = m
	return nil
}

// ----- map[string]uint -----

func encodeMapStringUint(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]uint)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteUint(uint64(v))
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteUint(uint64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteUint(uint64(v))
	}
	return nil
}

func decodeMapStringUint(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]uint)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, uint](d, p, len(names))
		for _, k := range names {
			vWide, err := d.ReadUint()
			if err != nil {
				return err
			}
			v := uint(vWide)
			m[k] = v
		}
		*(*map[string]uint)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, uint](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		vWide, err := d.ReadUint()
		if err != nil {
			return err
		}
		v := uint(vWide)
		m[k] = v
	}
	*(*map[string]uint)(p) = m
	return nil
}

// ----- map[string]uint64 -----

func encodeMapStringUint64(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]uint64)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteUint(uint64(v))
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteUint(uint64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteUint(uint64(v))
	}
	return nil
}

func decodeMapStringUint64(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]uint64)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, uint64](d, p, len(names))
		for _, k := range names {
			v, err := d.ReadUint()
			if err != nil {
				return err
			}
			m[k] = v
		}
		*(*map[string]uint64)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, uint64](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		v, err := d.ReadUint()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[string]uint64)(p) = m
	return nil
}

// ----- map[string]float32 -----

func encodeMapStringFloat32(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]float32)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteFloat32(v)
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteFloat32(v)
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteFloat32(v)
	}
	return nil
}

func decodeMapStringFloat32(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]float32)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, float32](d, p, len(names))
		for _, k := range names {
			v, err := d.ReadFloat32()
			if err != nil {
				return err
			}
			m[k] = v
		}
		*(*map[string]float32)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, float32](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		v, err := d.ReadFloat32()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[string]float32)(p) = m
	return nil
}

// ----- map[string]float64 -----

func encodeMapStringFloat64(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]float64)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteFloat64(v)
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteFloat64(v)
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteFloat64(v)
	}
	return nil
}

func decodeMapStringFloat64(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]float64)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, float64](d, p, len(names))
		for _, k := range names {
			v, err := d.ReadFloat64()
			if err != nil {
				return err
			}
			m[k] = v
		}
		*(*map[string]float64)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, float64](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		v, err := d.ReadFloat64()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[string]float64)(p) = m
	return nil
}

// ----- map[string][]byte -----

func encodeMapStringBytes(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string][]byte)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteBytes(v)
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteBytes(v)
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteBytes(v)
	}
	return nil
}

func decodeMapStringBytes(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string][]byte)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, []byte](d, p, len(names))
		for _, k := range names {
			v, err := d.ReadBytes()
			if err != nil {
				return err
			}
			m[k] = v
		}
		*(*map[string][]byte)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, []byte](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		v, err := d.ReadBytes()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[string][]byte)(p) = m
	return nil
}

// ----- map[string][]string -----

func encodeMapStringStringSlice(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string][]string)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			e.WriteArrayHeader(len(v))
			for _, sv := range v {
				e.WriteString(sv)
			}
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			e.WriteArrayHeader(len(v))
			for _, sv := range v {
				e.WriteString(sv)
			}
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		e.WriteArrayHeader(len(v))
		for _, sv := range v {
			e.WriteString(sv)
		}
	}
	return nil
}

func decodeMapStringStringSlice(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string][]string)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, []string](d, p, len(names))
		for _, k := range names {
			hdrN, err := d.ReadArrayHeader()
			if err != nil {
				return err
			}
			if err := d.CheckLength(hdrN, 1); err != nil {
				return err
			}
			v := make([]string, hdrN)
			for i := range hdrN {
				sv, err := d.ReadString()
				if err != nil {
					return err
				}
				v[i] = sv
			}
			m[k] = v
		}
		*(*map[string][]string)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, []string](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		hdrN, err := d.ReadArrayHeader()
		if err != nil {
			return err
		}
		if err := d.CheckLength(hdrN, 1); err != nil {
			return err
		}
		v := make([]string, hdrN)
		for i := range hdrN {
			sv, err := d.ReadString()
			if err != nil {
				return err
			}
			v[i] = sv
		}
		m[k] = v
	}
	*(*map[string][]string)(p) = m
	return nil
}

// ----- map[string]any -----

func encodeMapStringAny(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[string]any)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	if len(m) > 0 && e.state != nil && e.opts.Has(OptMapShape) && e.opts.Has(OptDense) {
		for _, k := range mapStringShapeOrder(e, m) {
			v := m[k]
			if err := encodeReflect(e, v); err != nil {
				return err
			}
		}
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []string
		if e.state != nil {
			keys = e.state.canonKeysStr[:0]
		} else {
			keys = make([]string, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysStr = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteString(k)
			if err := encodeReflect(e, v); err != nil {
				return err
			}
		}
		return nil
	}
	for k, v := range m {
		e.WriteString(k)
		if err := encodeReflect(e, v); err != nil {
			return err
		}
	}
	return nil
}

func decodeMapStringAny(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[string]any)(p) = nil
		return nil
	}
	if t == tagMapShape {
		names, err := decodeMapStringShapeHeader(d)
		if err != nil {
			return err
		}
		m := reuseOrMakeMap[string, any](d, p, len(names))
		for _, k := range names {
			v, err := decodeAny(d)
			if err != nil {
				return err
			}
			m[k] = v
		}
		*(*map[string]any)(p) = m
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[string, any](d, p, n)
	for range n {
		kb, err := d.readStringBytes()
		if err != nil {
			return err
		}
		k := d.keyCache.Make(kb)
		v, err := decodeAny(d)
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[string]any)(p) = m
	return nil
}

// ----- map[int]string -----

func encodeMapIntString(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[int]string)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []int64
		if e.state != nil {
			keys = e.state.canonKeysI64[:0]
		} else {
			keys = make([]int64, 0, len(m))
		}
		for k := range m {
			keys = append(keys, int64(k))
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysI64 = keys
		}
		for _, sk := range keys {
			k := int(sk)
			v := m[k]
			e.WriteInt(int64(k))
			e.WriteString(v)
		}
		return nil
	}
	for k, v := range m {
		e.WriteInt(int64(k))
		e.WriteString(v)
	}
	return nil
}

func decodeMapIntString(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[int]string)(p) = nil
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[int, string](d, p, n)
	for range n {
		kWide, err := d.ReadInt()
		if err != nil {
			return err
		}
		k := int(kWide)
		v, err := d.ReadString()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[int]string)(p) = m
	return nil
}

// ----- map[int]int -----

func encodeMapIntInt(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[int]int)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []int64
		if e.state != nil {
			keys = e.state.canonKeysI64[:0]
		} else {
			keys = make([]int64, 0, len(m))
		}
		for k := range m {
			keys = append(keys, int64(k))
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysI64 = keys
		}
		for _, sk := range keys {
			k := int(sk)
			v := m[k]
			e.WriteInt(int64(k))
			e.WriteInt(int64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteInt(int64(k))
		e.WriteInt(int64(v))
	}
	return nil
}

func decodeMapIntInt(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[int]int)(p) = nil
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[int, int](d, p, n)
	for range n {
		kWide, err := d.ReadInt()
		if err != nil {
			return err
		}
		k := int(kWide)
		vWide, err := d.ReadInt()
		if err != nil {
			return err
		}
		v := int(vWide)
		m[k] = v
	}
	*(*map[int]int)(p) = m
	return nil
}

// ----- map[int]int64 -----

func encodeMapIntInt64(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[int]int64)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []int64
		if e.state != nil {
			keys = e.state.canonKeysI64[:0]
		} else {
			keys = make([]int64, 0, len(m))
		}
		for k := range m {
			keys = append(keys, int64(k))
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysI64 = keys
		}
		for _, sk := range keys {
			k := int(sk)
			v := m[k]
			e.WriteInt(int64(k))
			e.WriteInt(int64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteInt(int64(k))
		e.WriteInt(int64(v))
	}
	return nil
}

func decodeMapIntInt64(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[int]int64)(p) = nil
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[int, int64](d, p, n)
	for range n {
		kWide, err := d.ReadInt()
		if err != nil {
			return err
		}
		k := int(kWide)
		v, err := d.ReadInt()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[int]int64)(p) = m
	return nil
}

// ----- map[int]any -----

func encodeMapIntAny(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[int]any)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []int64
		if e.state != nil {
			keys = e.state.canonKeysI64[:0]
		} else {
			keys = make([]int64, 0, len(m))
		}
		for k := range m {
			keys = append(keys, int64(k))
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysI64 = keys
		}
		for _, sk := range keys {
			k := int(sk)
			v := m[k]
			e.WriteInt(int64(k))
			if err := encodeReflect(e, v); err != nil {
				return err
			}
		}
		return nil
	}
	for k, v := range m {
		e.WriteInt(int64(k))
		if err := encodeReflect(e, v); err != nil {
			return err
		}
	}
	return nil
}

func decodeMapIntAny(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[int]any)(p) = nil
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[int, any](d, p, n)
	for range n {
		kWide, err := d.ReadInt()
		if err != nil {
			return err
		}
		k := int(kWide)
		v, err := decodeAny(d)
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[int]any)(p) = m
	return nil
}

// ----- map[int64]string -----

func encodeMapInt64String(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[int64]string)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []int64
		if e.state != nil {
			keys = e.state.canonKeysI64[:0]
		} else {
			keys = make([]int64, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysI64 = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteInt(int64(k))
			e.WriteString(v)
		}
		return nil
	}
	for k, v := range m {
		e.WriteInt(int64(k))
		e.WriteString(v)
	}
	return nil
}

func decodeMapInt64String(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[int64]string)(p) = nil
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[int64, string](d, p, n)
	for range n {
		k, err := d.ReadInt()
		if err != nil {
			return err
		}
		v, err := d.ReadString()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[int64]string)(p) = m
	return nil
}

// ----- map[int64]int64 -----

func encodeMapInt64Int64(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[int64]int64)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []int64
		if e.state != nil {
			keys = e.state.canonKeysI64[:0]
		} else {
			keys = make([]int64, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysI64 = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteInt(int64(k))
			e.WriteInt(int64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteInt(int64(k))
		e.WriteInt(int64(v))
	}
	return nil
}

func decodeMapInt64Int64(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[int64]int64)(p) = nil
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[int64, int64](d, p, n)
	for range n {
		k, err := d.ReadInt()
		if err != nil {
			return err
		}
		v, err := d.ReadInt()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[int64]int64)(p) = m
	return nil
}

// ----- map[int64]any -----

func encodeMapInt64Any(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[int64]any)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []int64
		if e.state != nil {
			keys = e.state.canonKeysI64[:0]
		} else {
			keys = make([]int64, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysI64 = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteInt(int64(k))
			if err := encodeReflect(e, v); err != nil {
				return err
			}
		}
		return nil
	}
	for k, v := range m {
		e.WriteInt(int64(k))
		if err := encodeReflect(e, v); err != nil {
			return err
		}
	}
	return nil
}

func decodeMapInt64Any(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[int64]any)(p) = nil
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[int64, any](d, p, n)
	for range n {
		k, err := d.ReadInt()
		if err != nil {
			return err
		}
		v, err := decodeAny(d)
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[int64]any)(p) = m
	return nil
}

// ----- map[uint64]string -----

func encodeMapUint64String(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[uint64]string)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []uint64
		if e.state != nil {
			keys = e.state.canonKeysU64[:0]
		} else {
			keys = make([]uint64, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysU64 = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteUint(uint64(k))
			e.WriteString(v)
		}
		return nil
	}
	for k, v := range m {
		e.WriteUint(uint64(k))
		e.WriteString(v)
	}
	return nil
}

func decodeMapUint64String(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[uint64]string)(p) = nil
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[uint64, string](d, p, n)
	for range n {
		k, err := d.ReadUint()
		if err != nil {
			return err
		}
		v, err := d.ReadString()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[uint64]string)(p) = m
	return nil
}

// ----- map[uint64]uint64 -----

func encodeMapUint64Uint64(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[uint64]uint64)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []uint64
		if e.state != nil {
			keys = e.state.canonKeysU64[:0]
		} else {
			keys = make([]uint64, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysU64 = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteUint(uint64(k))
			e.WriteUint(uint64(v))
		}
		return nil
	}
	for k, v := range m {
		e.WriteUint(uint64(k))
		e.WriteUint(uint64(v))
	}
	return nil
}

func decodeMapUint64Uint64(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[uint64]uint64)(p) = nil
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[uint64, uint64](d, p, n)
	for range n {
		k, err := d.ReadUint()
		if err != nil {
			return err
		}
		v, err := d.ReadUint()
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[uint64]uint64)(p) = m
	return nil
}

// ----- map[uint64]any -----

func encodeMapUint64Any(e *Encoder, p unsafe.Pointer) error {
	m := *(*map[uint64]any)(p)
	if m == nil {
		e.WriteNil()
		return nil
	}
	e.WriteMapHeader(len(m))
	if e.opts.Has(OptCanonical) {
		var keys []uint64
		if e.state != nil {
			keys = e.state.canonKeysU64[:0]
		} else {
			keys = make([]uint64, 0, len(m))
		}
		for k := range m {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		if e.state != nil {
			e.state.canonKeysU64 = keys
		}
		for _, sk := range keys {
			k := sk
			v := m[k]
			e.WriteUint(uint64(k))
			if err := encodeReflect(e, v); err != nil {
				return err
			}
		}
		return nil
	}
	for k, v := range m {
		e.WriteUint(uint64(k))
		if err := encodeReflect(e, v); err != nil {
			return err
		}
	}
	return nil
}

func decodeMapUint64Any(d *Decoder, p unsafe.Pointer) error {
	t, err := d.peekTag()
	if err != nil {
		return err
	}
	if t == tagNil {
		d.i++
		*(*map[uint64]any)(p) = nil
		return nil
	}
	n, err := d.ReadMapHeader()
	if err != nil {
		return err
	}
	if err := d.CheckLength(n, 2); err != nil {
		return err
	}
	m := reuseOrMakeMap[uint64, any](d, p, n)
	for range n {
		k, err := d.ReadUint()
		if err != nil {
			return err
		}
		v, err := decodeAny(d)
		if err != nil {
			return err
		}
		m[k] = v
	}
	*(*map[uint64]any)(p) = m
	return nil
}

// installMapFastPath returns (encode, decode, true) when t matches
// one of the generated typed-map shapes; otherwise (_, _, false). The
// table is generated; edit internal/mapsgen/main.go to add or remove
// pairs.
func installMapFastPath(t reflect.Type) (
	enc func(*Encoder, unsafe.Pointer) error,
	dec func(*Decoder, unsafe.Pointer) error,
	ok bool,
) {
	switch t {
	case reflect.TypeFor[map[string]string]():
		return encodeMapStringString, decodeMapStringString, true
	case reflect.TypeFor[map[string]bool]():
		return encodeMapStringBool, decodeMapStringBool, true
	case reflect.TypeFor[map[string]int8]():
		return encodeMapStringInt8, decodeMapStringInt8, true
	case reflect.TypeFor[map[string]int16]():
		return encodeMapStringInt16, decodeMapStringInt16, true
	case reflect.TypeFor[map[string]int32]():
		return encodeMapStringInt32, decodeMapStringInt32, true
	case reflect.TypeFor[map[string]int]():
		return encodeMapStringInt, decodeMapStringInt, true
	case reflect.TypeFor[map[string]int64]():
		return encodeMapStringInt64, decodeMapStringInt64, true
	case reflect.TypeFor[map[string]uint8]():
		return encodeMapStringUint8, decodeMapStringUint8, true
	case reflect.TypeFor[map[string]uint16]():
		return encodeMapStringUint16, decodeMapStringUint16, true
	case reflect.TypeFor[map[string]uint32]():
		return encodeMapStringUint32, decodeMapStringUint32, true
	case reflect.TypeFor[map[string]uint]():
		return encodeMapStringUint, decodeMapStringUint, true
	case reflect.TypeFor[map[string]uint64]():
		return encodeMapStringUint64, decodeMapStringUint64, true
	case reflect.TypeFor[map[string]float32]():
		return encodeMapStringFloat32, decodeMapStringFloat32, true
	case reflect.TypeFor[map[string]float64]():
		return encodeMapStringFloat64, decodeMapStringFloat64, true
	case reflect.TypeFor[map[string][]byte]():
		return encodeMapStringBytes, decodeMapStringBytes, true
	case reflect.TypeFor[map[string][]string]():
		return encodeMapStringStringSlice, decodeMapStringStringSlice, true
	case reflect.TypeFor[map[string]any]():
		return encodeMapStringAny, decodeMapStringAny, true
	case reflect.TypeFor[map[int]string]():
		return encodeMapIntString, decodeMapIntString, true
	case reflect.TypeFor[map[int]int]():
		return encodeMapIntInt, decodeMapIntInt, true
	case reflect.TypeFor[map[int]int64]():
		return encodeMapIntInt64, decodeMapIntInt64, true
	case reflect.TypeFor[map[int]any]():
		return encodeMapIntAny, decodeMapIntAny, true
	case reflect.TypeFor[map[int64]string]():
		return encodeMapInt64String, decodeMapInt64String, true
	case reflect.TypeFor[map[int64]int64]():
		return encodeMapInt64Int64, decodeMapInt64Int64, true
	case reflect.TypeFor[map[int64]any]():
		return encodeMapInt64Any, decodeMapInt64Any, true
	case reflect.TypeFor[map[uint64]string]():
		return encodeMapUint64String, decodeMapUint64String, true
	case reflect.TypeFor[map[uint64]uint64]():
		return encodeMapUint64Uint64, decodeMapUint64Uint64, true
	case reflect.TypeFor[map[uint64]any]():
		return encodeMapUint64Any, decodeMapUint64Any, true
	}
	return nil, nil, false
}
