package cgsample

import (
	"testing"
	"time"

	qdf "github.com/alex60217101990/qdf"
)

// TestGenEmbedTimeRoundTrip guards the appendFields embedded-codec gate. An
// embedded time.Time used to be flattened by the generator (its fields are
// unexported, so the flatten produced zero fields and silently dropped the
// value, diverging from the reflect path which encodes it as one "Time"
// field). Round-trips the generated path and cross-decodes via reflect.
func TestGenEmbedTimeRoundTrip(t *testing.T) {
	in := GenEmbedTime{Time: time.Unix(1_700_000_123, 456_000_000).UTC(), N: 42}

	b, err := in.MarshalQDF(nil)
	if err != nil {
		t.Fatalf("MarshalQDF: %v", err)
	}

	var out GenEmbedTime
	if _, err := out.UnmarshalQDF(b); err != nil {
		t.Fatalf("generated UnmarshalQDF: %v", err)
	}
	if !out.Time.Equal(in.Time) || out.N != in.N {
		t.Fatalf("generated round-trip mismatch: in=%+v out=%+v", in, out)
	}

	// Cross-decode via the reflect path: layouts must agree.
	var out2 GenEmbedTime
	if err := qdf.Unmarshal(b, &out2); err != nil {
		t.Fatalf("reflect Unmarshal of generated bytes: %v", err)
	}
	if !out2.Time.Equal(in.Time) || out2.N != in.N {
		t.Fatalf("cross-path mismatch: in=%+v out=%+v", in, out2)
	}

	// And the reverse: reflect encode, generated decode.
	rb, err := qdf.Marshal(&in, qdf.OptBalanced)
	if err != nil {
		t.Fatalf("reflect Marshal: %v", err)
	}
	var out3 GenEmbedTime
	if _, err := out3.UnmarshalQDF(rb); err != nil {
		t.Fatalf("generated decode of reflect bytes: %v", err)
	}
	if !out3.Time.Equal(in.Time) || out3.N != in.N {
		t.Fatalf("reverse cross-path mismatch: in=%+v out=%+v", in, out3)
	}
}
