// Code generated by qdfgen; DO NOT EDIT.

package cgsample

import (
	"github.com/alex60217101990/qdf"
	"time"
)

// Pre-encoded field-name headers (fixstr / strN). Lets the hot path
// emit a name with a single append, no per-call sizing.
var (
	qdfFieldHdr_base_a_1   = []byte{0x86, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x61}
	qdfFieldHdr_base_b_2   = []byte{0x86, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x62}
	qdfFieldHdr_labels_3   = []byte{0x86, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73}
	qdfFieldHdr_ptr_4      = []byte{0x83, 0x70, 0x74, 0x72}
	qdfFieldHdr_tail_5     = []byte{0x84, 0x74, 0x61, 0x69, 0x6c}
	qdfFieldHdr_ts_17      = []byte{0x82, 0x74, 0x73}
	qdfFieldHdr_level_18   = []byte{0x85, 0x6c, 0x65, 0x76, 0x65, 0x6c}
	qdfFieldHdr_code_19    = []byte{0x84, 0x63, 0x6f, 0x64, 0x65}
	qdfFieldHdr_msg_20     = []byte{0x83, 0x6d, 0x73, 0x67}
	qdfFieldHdr_source_26  = []byte{0x86, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65}
	qdfFieldHdr_events_27  = []byte{0x86, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73}
	qdfFieldHdr_value_50   = []byte{0x85, 0x76, 0x61, 0x6c, 0x75, 0x65}
	qdfFieldHdr_count_51   = []byte{0x85, 0x63, 0x6f, 0x75, 0x6e, 0x74}
	qdfFieldHdr_ok_52      = []byte{0x82, 0x6f, 0x6b}
	qdfFieldHdr_ratio_53   = []byte{0x85, 0x72, 0x61, 0x74, 0x69, 0x6f}
	qdfFieldHdr_name_59    = []byte{0x84, 0x6e, 0x61, 0x6d, 0x65}
	qdfFieldHdr_metrics_60 = []byte{0x87, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73}
	qdfFieldHdr_first_80   = []byte{0x85, 0x66, 0x69, 0x72, 0x73, 0x74}
	qdfFieldHdr_last_81    = []byte{0x84, 0x6c, 0x61, 0x73, 0x74}
	qdfFieldHdr_names_84   = []byte{0x85, 0x6e, 0x61, 0x6d, 0x65, 0x73}
	qdfFieldHdr_id_100     = []byte{0x82, 0x69, 0x64}
	qdfFieldHdr_inner_101  = []byte{0x85, 0x69, 0x6e, 0x6e, 0x65, 0x72}
	qdfFieldHdr_tags_102   = []byte{0x84, 0x74, 0x61, 0x67, 0x73}
	qdfFieldHdr_x_112      = []byte{0x81, 0x78}
	qdfFieldHdr_y_113      = []byte{0x81, 0x79}
	qdfFieldHdr_rows_116   = []byte{0x84, 0x72, 0x6f, 0x77, 0x73}
	qdfFieldHdr_age_139    = []byte{0x83, 0x61, 0x67, 0x65}
	qdfFieldHdr_active_140 = []byte{0x86, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65}
	qdfFieldHdr_score_141  = []byte{0x85, 0x73, 0x63, 0x6f, 0x72, 0x65}
	qdfFieldHdr_meta_142   = []byte{0x84, 0x6d, 0x65, 0x74, 0x61}
	qdfFieldHdr_when_143   = []byte{0x84, 0x77, 0x68, 0x65, 0x6e}
	qdfFieldHdr_buf_144    = []byte{0x83, 0x62, 0x75, 0x66}
	qdfFieldHdr_opt_145    = []byte{0x83, 0x6f, 0x70, 0x74}
	qdfFieldHdr_counts_146 = []byte{0x86, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73}
)

// Columnar shape descriptors: per element-type column names and kind
// bytes for the monomorphized tagColStruct transpose path.
var qdfColNames_GenEvent = []string{"ts", "level", "code", "msg"}
var qdfColKinds_GenEvent = []byte{0x05, 0x04, 0x00, 0x04}
var qdfColNames_GenMetric = []string{"ts", "value", "count", "ok", "ratio"}
var qdfColKinds_GenMetric = []byte{0x00, 0x02, 0x01, 0x03, 0x06}
var qdfColNames_GenName = []string{"first", "last"}
var qdfColKinds_GenName = []byte{0x04, 0x04}
var qdfHybNames_GenRow = []string{"id", "name", "inner", "tags"}
var qdfHybKinds_GenRow = []byte{0x00, 0x04, 0xff, 0xff}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *Edge) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_Edge byte
var qdfFieldHdrs_Edge = [][]byte{qdfFieldHdr_base_a_1, qdfFieldHdr_base_b_2, qdfFieldHdr_labels_3, qdfFieldHdr_ptr_4, qdfFieldHdr_tail_5}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *Edge) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_Edge, qdfFieldHdrs_Edge)
	e.WriteInt(int64(v.EmbeddedBase.BaseA))
	e.WriteString(string(v.EmbeddedBase.BaseB))
	if v.Labels == nil {
		e.WriteNil()
	} else {
		e.WriteMapHeader(len(v.Labels))
		for k6, vv7 := range v.Labels {
			e.WriteString(string(k6))
			e.WriteInt(int64(vv7))
		}
	}
	if v.Ptr == nil {
		e.WriteNil()
	} else {
		e.WriteString(string((*v.Ptr)))
	}
	e.WriteInt(int64(v.Tail))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *Edge) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *Edge) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "base_a":
		{
			rv8, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.EmbeddedBase.BaseA = int(rv8)
		}
	case "base_b":
		{
			rv9, err := d.ReadString()
			if err != nil {
				return err
			}
			v.EmbeddedBase.BaseB = rv9
		}
	case "labels":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Labels = nil
			} else {
				n10, err := d.ReadMapHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n10, 1); err != nil {
					return err
				}
				v.Labels = make(map[Label]int, n10)
				for range n10 {
					var k11 Label
					var vv12 int
					kb13, err := d.ReadStringBytes()
					if err != nil {
						return err
					}
					k11 = Label(d.InternKey(kb13))
					{
						rv14, err := d.ReadInt()
						if err != nil {
							return err
						}
						vv12 = int(rv14)
					}
					v.Labels[k11] = vv12
				}
			}
		}
	case "ptr":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Ptr = nil
			} else {
				v.Ptr = new(Label)
				{
					nv15, err := d.ReadString()
					if err != nil {
						return err
					}
					(*v.Ptr) = Label(nv15)
				}
			}
		}
	case "tail":
		{
			rv16, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.Tail = int(rv16)
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *Edge) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *Edge) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *Edge) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenEvent) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenEvent byte
var qdfFieldHdrs_GenEvent = [][]byte{qdfFieldHdr_ts_17, qdfFieldHdr_level_18, qdfFieldHdr_code_19, qdfFieldHdr_msg_20}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenEvent) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenEvent, qdfFieldHdrs_GenEvent)
	{
		_t := (v.TS).UTC()
		e.WriteTimestamp(_t.Unix(), uint32(_t.Nanosecond()))
	}
	e.WriteString(string(v.Level))
	e.WriteInt(int64(v.Code))
	e.WriteString(string(v.Msg))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenEvent) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenEvent) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "ts":
		{
			sec21, nsec22, err := d.ReadTimestamp()
			if err != nil {
				return err
			}
			v.TS = time.Unix(sec21, int64(nsec22)).UTC()
		}
	case "level":
		{
			rv23, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Level = rv23
		}
	case "code":
		{
			rv24, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.Code = int32(rv24)
		}
	case "msg":
		{
			rv25, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Msg = rv25
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenEvent) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenEvent) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenEvent) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenEventLog) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenEventLog byte
var qdfFieldHdrs_GenEventLog = [][]byte{qdfFieldHdr_source_26, qdfFieldHdr_events_27}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenEventLog) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenEventLog, qdfFieldHdrs_GenEventLog)
	e.WriteString(string(v.Source))
	if v.Events == nil {
		e.WriteNil()
	} else if len(v.Events) >= 16 { // columnarMinElems
		col28 := v.Events
		e.WriteColStructHeader(len(col28), qdfColNames_GenEvent, qdfColKinds_GenEvent)
		sec30 := e.ScratchInt(len(col28))
		ns31 := e.ScratchUint(len(col28))
		for i := range col28 {
			t32 := col28[i].TS.UTC()
			sec30[i] = t32.Unix()
			ns31[i] = uint64(t32.Nanosecond())
		}
		if err := e.WriteTimeColumn(sec30, ns31); err != nil {
			return err
		}
		c33 := e.ScratchString(len(col28))
		for i := range col28 {
			c33[i] = string(col28[i].Level)
		}
		e.WriteStringColumn(c33)
		c34 := e.ScratchInt(len(col28))
		for i := range col28 {
			c34[i] = int64(col28[i].Code)
		}
		if err := e.WriteIntColumn(c34); err != nil {
			return err
		}
		c35 := e.ScratchString(len(col28))
		for i := range col28 {
			c35[i] = string(col28[i].Msg)
		}
		e.WriteStringColumn(c35)
	} else {
		e.WriteArrayHeader(len(v.Events))
		for i36 := range v.Events {
			if err := qdf.EncodeNested(e, &v.Events[i36]); err != nil {
				return err
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenEventLog) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenEventLog) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "source":
		{
			rv37, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Source = rv37
		}
	case "events":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Events = nil
			} else if d.PeekColStruct() {
				n38, names39, kinds40, err := d.ReadColStructHeader()
				if err != nil {
					return err
				}
				_ = kinds40
				v.Events = make([]GenEvent, n38)
				for ci41 := range names39 {
					switch names39[ci41] {
					case "ts":
						sec43, ns44, err := d.ReadTimeColumn(n38)
						if err != nil {
							return err
						}
						for i := range sec43 {
							v.Events[i].TS = time.Unix(sec43[i], int64(ns44[i])).UTC()
						}
					case "level":
						col45, err := d.ReadStringColumn(n38)
						if err != nil {
							return err
						}
						for i := range col45 {
							v.Events[i].Level = string(col45[i])
						}
					case "code":
						col46, err := d.ReadIntColumn(n38)
						if err != nil {
							return err
						}
						for i := range col46 {
							v.Events[i].Code = int32(col46[i])
						}
					case "msg":
						col47, err := d.ReadStringColumn(n38)
						if err != nil {
							return err
						}
						for i := range col47 {
							v.Events[i].Msg = string(col47[i])
						}
					default:
						return qdf.ErrTypeMismatch
					}
				}
			} else {
				n48, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n48, 1); err != nil {
					return err
				}
				v.Events = make([]GenEvent, n48)
				for i49 := range n48 {
					if err := qdf.DecodeNested(d, &v.Events[i49]); err != nil {
						return err
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenEventLog) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenEventLog) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenEventLog) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenMetric) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenMetric byte
var qdfFieldHdrs_GenMetric = [][]byte{qdfFieldHdr_ts_17, qdfFieldHdr_value_50, qdfFieldHdr_count_51, qdfFieldHdr_ok_52, qdfFieldHdr_ratio_53}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenMetric) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenMetric, qdfFieldHdrs_GenMetric)
	e.WriteInt(int64(v.TS))
	e.WriteFloat64(float64(v.Value))
	e.WriteUint(uint64(v.Count))
	e.WriteBool(bool(v.OK))
	e.WriteFloat32(float32(v.Ratio))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenMetric) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenMetric) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "ts":
		{
			rv54, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.TS = int64(rv54)
		}
	case "value":
		{
			rv55, err := d.ReadFloat64()
			if err != nil {
				return err
			}
			v.Value = rv55
		}
	case "count":
		{
			rv56, err := d.ReadUint()
			if err != nil {
				return err
			}
			v.Count = uint32(rv56)
		}
	case "ok":
		{
			rv57, err := d.ReadBool()
			if err != nil {
				return err
			}
			v.OK = rv57
		}
	case "ratio":
		{
			rv58, err := d.ReadFloat32()
			if err != nil {
				return err
			}
			v.Ratio = rv58
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenMetric) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenMetric) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenMetric) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenMetricBatch) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenMetricBatch byte
var qdfFieldHdrs_GenMetricBatch = [][]byte{qdfFieldHdr_name_59, qdfFieldHdr_metrics_60}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenMetricBatch) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenMetricBatch, qdfFieldHdrs_GenMetricBatch)
	e.WriteString(string(v.Name))
	if v.Metrics == nil {
		e.WriteNil()
	} else if len(v.Metrics) >= 16 { // columnarMinElems
		col61 := v.Metrics
		e.WriteColStructHeader(len(col61), qdfColNames_GenMetric, qdfColKinds_GenMetric)
		c62 := e.ScratchInt(len(col61))
		for i := range col61 {
			c62[i] = int64(col61[i].TS)
		}
		if err := e.WriteIntColumn(c62); err != nil {
			return err
		}
		c63 := e.ScratchFloat64(len(col61))
		for i := range col61 {
			c63[i] = float64(col61[i].Value)
		}
		if err := e.WriteFloat64Column(c63); err != nil {
			return err
		}
		c64 := e.ScratchUint(len(col61))
		for i := range col61 {
			c64[i] = uint64(col61[i].Count)
		}
		if err := e.WriteUintColumn(c64); err != nil {
			return err
		}
		c65 := e.ScratchBool(len(col61))
		for i := range col61 {
			c65[i] = col61[i].OK
		}
		if err := e.WriteBoolColumn(c65); err != nil {
			return err
		}
		c66 := e.ScratchFloat32(len(col61))
		for i := range col61 {
			c66[i] = float32(col61[i].Ratio)
		}
		if err := e.WriteFloat32Column(c66); err != nil {
			return err
		}
	} else {
		e.WriteArrayHeader(len(v.Metrics))
		for i67 := range v.Metrics {
			if err := qdf.EncodeNested(e, &v.Metrics[i67]); err != nil {
				return err
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenMetricBatch) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenMetricBatch) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "name":
		{
			rv68, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Name = rv68
		}
	case "metrics":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Metrics = nil
			} else if d.PeekColStruct() {
				n69, names70, kinds71, err := d.ReadColStructHeader()
				if err != nil {
					return err
				}
				_ = kinds71
				v.Metrics = make([]GenMetric, n69)
				for ci72 := range names70 {
					switch names70[ci72] {
					case "ts":
						col73, err := d.ReadIntColumn(n69)
						if err != nil {
							return err
						}
						for i := range col73 {
							v.Metrics[i].TS = int64(col73[i])
						}
					case "value":
						col74, err := d.ReadFloat64Column(n69)
						if err != nil {
							return err
						}
						for i := range col74 {
							v.Metrics[i].Value = float64(col74[i])
						}
					case "count":
						col75, err := d.ReadUintColumn(n69)
						if err != nil {
							return err
						}
						for i := range col75 {
							v.Metrics[i].Count = uint32(col75[i])
						}
					case "ok":
						col76, err := d.ReadBoolColumn(n69)
						if err != nil {
							return err
						}
						for i := range col76 {
							v.Metrics[i].OK = col76[i]
						}
					case "ratio":
						col77, err := d.ReadFloat32Column(n69)
						if err != nil {
							return err
						}
						for i := range col77 {
							v.Metrics[i].Ratio = float32(col77[i])
						}
					default:
						return qdf.ErrTypeMismatch
					}
				}
			} else {
				n78, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n78, 1); err != nil {
					return err
				}
				v.Metrics = make([]GenMetric, n78)
				for i79 := range n78 {
					if err := qdf.DecodeNested(d, &v.Metrics[i79]); err != nil {
						return err
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenMetricBatch) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenMetricBatch) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenMetricBatch) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenName) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenName byte
var qdfFieldHdrs_GenName = [][]byte{qdfFieldHdr_first_80, qdfFieldHdr_last_81}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenName) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenName, qdfFieldHdrs_GenName)
	e.WriteString(string(v.First))
	e.WriteString(string(v.Last))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenName) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenName) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "first":
		{
			rv82, err := d.ReadString()
			if err != nil {
				return err
			}
			v.First = rv82
		}
	case "last":
		{
			rv83, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Last = rv83
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenName) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenName) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenName) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenNameList) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenNameList byte
var qdfFieldHdrs_GenNameList = [][]byte{qdfFieldHdr_names_84}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenNameList) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenNameList, qdfFieldHdrs_GenNameList)
	if v.Names == nil {
		e.WriteNil()
	} else if len(v.Names) >= 16 { // columnarMinElems
		col85 := v.Names
		ben86 := false
		pb87 := e.ScratchString(min(len(col85), 32))
		for i := range pb87 {
			pb87[i] = string(col85[i].First)
		}
		if qdf.StringColumnsBeneficial(pb87) {
			ben86 = true
		}
		for i := range pb87 {
			pb87[i] = string(col85[i].Last)
		}
		if qdf.StringColumnsBeneficial(pb87) {
			ben86 = true
		}
		if ben86 {
			e.WriteColStructHeader(len(col85), qdfColNames_GenName, qdfColKinds_GenName)
			c88 := e.ScratchString(len(col85))
			for i := range col85 {
				c88[i] = string(col85[i].First)
			}
			e.WriteStringColumn(c88)
			c89 := e.ScratchString(len(col85))
			for i := range col85 {
				c89[i] = string(col85[i].Last)
			}
			e.WriteStringColumn(c89)
		} else {
			e.WriteArrayHeader(len(col85))
			for i90 := range col85 {
				if err := qdf.EncodeNested(e, &col85[i90]); err != nil {
					return err
				}
			}
		}
	} else {
		e.WriteArrayHeader(len(v.Names))
		for i91 := range v.Names {
			if err := qdf.EncodeNested(e, &v.Names[i91]); err != nil {
				return err
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenNameList) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenNameList) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "names":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Names = nil
			} else if d.PeekColStruct() {
				n92, names93, kinds94, err := d.ReadColStructHeader()
				if err != nil {
					return err
				}
				_ = kinds94
				v.Names = make([]GenName, n92)
				for ci95 := range names93 {
					switch names93[ci95] {
					case "first":
						col96, err := d.ReadStringColumn(n92)
						if err != nil {
							return err
						}
						for i := range col96 {
							v.Names[i].First = string(col96[i])
						}
					case "last":
						col97, err := d.ReadStringColumn(n92)
						if err != nil {
							return err
						}
						for i := range col97 {
							v.Names[i].Last = string(col97[i])
						}
					default:
						return qdf.ErrTypeMismatch
					}
				}
			} else {
				n98, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n98, 1); err != nil {
					return err
				}
				v.Names = make([]GenName, n98)
				for i99 := range n98 {
					if err := qdf.DecodeNested(d, &v.Names[i99]); err != nil {
						return err
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenNameList) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenNameList) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenNameList) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenRow) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenRow byte
var qdfFieldHdrs_GenRow = [][]byte{qdfFieldHdr_id_100, qdfFieldHdr_name_59, qdfFieldHdr_inner_101, qdfFieldHdr_tags_102}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenRow) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenRow, qdfFieldHdrs_GenRow)
	e.WriteInt(int64(v.ID))
	e.WriteString(string(v.Name))
	if err := qdf.EncodeNested(e, &v.Inner); err != nil {
		return err
	}
	if v.Tags == nil {
		e.WriteNil()
	} else {
		e.WriteMapHeader(len(v.Tags))
		for k103, vv104 := range v.Tags {
			e.WriteString(string(k103))
			e.WriteInt(int64(vv104))
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenRow) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenRow) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "id":
		{
			rv105, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.ID = int64(rv105)
		}
	case "name":
		{
			rv106, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Name = rv106
		}
	case "inner":
		if err := qdf.DecodeNested(d, &v.Inner); err != nil {
			return err
		}
	case "tags":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Tags = nil
			} else {
				n107, err := d.ReadMapHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n107, 1); err != nil {
					return err
				}
				v.Tags = make(map[string]int, n107)
				for range n107 {
					var k108 string
					var vv109 int
					kb110, err := d.ReadStringBytes()
					if err != nil {
						return err
					}
					k108 = string(d.InternKey(kb110))
					{
						rv111, err := d.ReadInt()
						if err != nil {
							return err
						}
						vv109 = int(rv111)
					}
					v.Tags[k108] = vv109
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenRow) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenRow) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenRow) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenRowInner) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenRowInner byte
var qdfFieldHdrs_GenRowInner = [][]byte{qdfFieldHdr_x_112, qdfFieldHdr_y_113}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenRowInner) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenRowInner, qdfFieldHdrs_GenRowInner)
	e.WriteInt(int64(v.X))
	e.WriteString(string(v.Y))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenRowInner) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenRowInner) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "x":
		{
			rv114, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.X = int(rv114)
		}
	case "y":
		{
			rv115, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Y = rv115
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenRowInner) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenRowInner) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenRowInner) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenRowSet) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenRowSet byte
var qdfFieldHdrs_GenRowSet = [][]byte{qdfFieldHdr_rows_116}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenRowSet) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenRowSet, qdfFieldHdrs_GenRowSet)
	if v.Rows == nil {
		e.WriteNil()
	} else if len(v.Rows) >= 16 { // columnarMinElems
		col117 := v.Rows
		e.WriteHybridColStructHeader(len(col117), qdfHybNames_GenRow, qdfHybKinds_GenRow)
		c118 := e.ScratchInt(len(col117))
		for i := range col117 {
			c118[i] = int64(col117[i].ID)
		}
		if err := e.WriteIntColumn(c118); err != nil {
			return err
		}
		c119 := e.ScratchString(len(col117))
		for i := range col117 {
			c119[i] = string(col117[i].Name)
		}
		e.WriteStringColumn(c119)
		for i120 := range col117 {
			if err := qdf.EncodeNested(e, &col117[i120].Inner); err != nil {
				return err
			}
			if col117[i120].Tags == nil {
				e.WriteNil()
			} else {
				e.WriteMapHeader(len(col117[i120].Tags))
				for k121, vv122 := range col117[i120].Tags {
					e.WriteString(string(k121))
					e.WriteInt(int64(vv122))
				}
			}
		}
	} else {
		e.WriteArrayHeader(len(v.Rows))
		for i123 := range v.Rows {
			if err := qdf.EncodeNested(e, &v.Rows[i123]); err != nil {
				return err
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenRowSet) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenRowSet) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "rows":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Rows = nil
			} else if d.PeekHybridColStruct() {
				n124, names125, kinds126, err := d.ReadHybridColStructHeader()
				if err != nil {
					return err
				}
				_ = names125
				_ = kinds126
				v.Rows = make([]GenRow, n124)
				col127, err := d.ReadIntColumn(n124)
				if err != nil {
					return err
				}
				for i := range col127 {
					v.Rows[i].ID = int64(col127[i])
				}
				col128, err := d.ReadStringColumn(n124)
				if err != nil {
					return err
				}
				for i := range col128 {
					v.Rows[i].Name = string(col128[i])
				}
				d.ClearColMaxLen()
				for i129 := range v.Rows {
					if err := qdf.DecodeNested(d, &v.Rows[i129].Inner); err != nil {
						return err
					}
					{
						isNil, err := d.IsNil()
						if err != nil {
							return err
						}
						if isNil {
							v.Rows[i129].Tags = nil
						} else {
							n130, err := d.ReadMapHeader()
							if err != nil {
								return err
							}
							if err := d.CheckLength(n130, 1); err != nil {
								return err
							}
							v.Rows[i129].Tags = make(map[string]int, n130)
							for range n130 {
								var k131 string
								var vv132 int
								kb133, err := d.ReadStringBytes()
								if err != nil {
									return err
								}
								k131 = string(d.InternKey(kb133))
								{
									rv134, err := d.ReadInt()
									if err != nil {
										return err
									}
									vv132 = int(rv134)
								}
								v.Rows[i129].Tags[k131] = vv132
							}
						}
					}
				}
			} else {
				n135, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n135, 1); err != nil {
					return err
				}
				v.Rows = make([]GenRow, n135)
				for i136 := range n135 {
					if err := qdf.DecodeNested(d, &v.Rows[i136]); err != nil {
						return err
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenRowSet) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenRowSet) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenRowSet) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *Inner) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_Inner byte
var qdfFieldHdrs_Inner = [][]byte{qdfFieldHdr_x_112, qdfFieldHdr_y_113}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *Inner) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_Inner, qdfFieldHdrs_Inner)
	e.WriteInt(int64(v.X))
	e.WriteFloat64(float64(v.Y))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *Inner) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *Inner) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "x":
		{
			rv137, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.X = int(rv137)
		}
	case "y":
		{
			rv138, err := d.ReadFloat64()
			if err != nil {
				return err
			}
			v.Y = rv138
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *Inner) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *Inner) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *Inner) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *Sample) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_Sample byte
var qdfFieldHdrs_Sample = [][]byte{qdfFieldHdr_name_59, qdfFieldHdr_age_139, qdfFieldHdr_active_140, qdfFieldHdr_score_141, qdfFieldHdr_tags_102, qdfFieldHdr_meta_142, qdfFieldHdr_inner_101, qdfFieldHdr_when_143, qdfFieldHdr_buf_144, qdfFieldHdr_opt_145, qdfFieldHdr_counts_146}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *Sample) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_Sample, qdfFieldHdrs_Sample)
	e.WriteString(string(v.Name))
	e.WriteInt(int64(v.Age))
	e.WriteBool(bool(v.Active))
	e.WriteFloat64(float64(v.Score))
	if v.Tags == nil {
		e.WriteNil()
	} else {
		e.WriteArrayHeader(len(v.Tags))
		for i147 := range v.Tags {
			e.WriteString(string(v.Tags[i147]))
		}
	}
	if v.Meta == nil {
		e.WriteNil()
	} else {
		e.WriteMapHeader(len(v.Meta))
		for k148, vv149 := range v.Meta {
			e.WriteString(string(k148))
			e.WriteString(string(vv149))
		}
	}
	if err := qdf.EncodeNested(e, &v.Inner); err != nil {
		return err
	}
	{
		_t := (v.When).UTC()
		e.WriteTimestamp(_t.Unix(), uint32(_t.Nanosecond()))
	}
	if v.Buf == nil {
		e.WriteNil()
	} else {
		e.WriteBytes([]byte(v.Buf))
	}
	if v.OptPtr == nil {
		e.WriteNil()
	} else {
		if err := qdf.EncodeNested(e, v.OptPtr); err != nil {
			return err
		}
	}
	e.WriteArrayHeader(3)
	for i150 := range v.Counts {
		e.WriteInt(int64(v.Counts[i150]))
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *Sample) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *Sample) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "name":
		{
			rv151, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Name = rv151
		}
	case "age":
		{
			rv152, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.Age = int(rv152)
		}
	case "active":
		{
			rv153, err := d.ReadBool()
			if err != nil {
				return err
			}
			v.Active = rv153
		}
	case "score":
		{
			rv154, err := d.ReadFloat64()
			if err != nil {
				return err
			}
			v.Score = rv154
		}
	case "tags":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Tags = nil
			} else {
				n155, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n155, 1); err != nil {
					return err
				}
				v.Tags = make([]string, n155)
				for i156 := range n155 {
					{
						rv157, err := d.ReadString()
						if err != nil {
							return err
						}
						v.Tags[i156] = rv157
					}
				}
			}
		}
	case "meta":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Meta = nil
			} else {
				n158, err := d.ReadMapHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n158, 1); err != nil {
					return err
				}
				v.Meta = make(map[string]string, n158)
				for range n158 {
					var k159 string
					var vv160 string
					kb161, err := d.ReadStringBytes()
					if err != nil {
						return err
					}
					k159 = string(d.InternKey(kb161))
					{
						rv162, err := d.ReadString()
						if err != nil {
							return err
						}
						vv160 = rv162
					}
					v.Meta[k159] = vv160
				}
			}
		}
	case "inner":
		if err := qdf.DecodeNested(d, &v.Inner); err != nil {
			return err
		}
	case "when":
		{
			sec163, nsec164, err := d.ReadTimestamp()
			if err != nil {
				return err
			}
			v.When = time.Unix(sec163, int64(nsec164)).UTC()
		}
	case "buf":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Buf = nil
			} else {
				_v, err := d.ReadBytes()
				if err != nil {
					return err
				}
				v.Buf = _v
			}
		}
	case "opt":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.OptPtr = nil
			} else {
				v.OptPtr = new(Inner)
				if err := qdf.DecodeNested(d, v.OptPtr); err != nil {
					return err
				}
			}
		}
	case "counts":
		{
			n165, err := d.ReadArrayHeader()
			if err != nil {
				return err
			}
			if n165 != 3 {
				return qdf.ErrTypeMismatch
			}
			for i166 := range 3 {
				{
					rv167, err := d.ReadInt()
					if err != nil {
						return err
					}
					v.Counts[i166] = int32(rv167)
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *Sample) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *Sample) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *Sample) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}
