// Code generated by qdfgen; DO NOT EDIT.

package cgsample

import (
	"cmp"
	"github.com/alex60217101990/qdf"
	"math"
	"slices"
	"time"
	"unsafe"
)

// Pre-encoded field-name headers (fixstr / strN). Lets the hot path
// emit a name with a single append, no per-call sizing.
var (
	qdfFieldHdr_base_a_1   = []byte{0x86, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x61}
	qdfFieldHdr_base_b_2   = []byte{0x86, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x62}
	qdfFieldHdr_labels_3   = []byte{0x86, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73}
	qdfFieldHdr_ptr_4      = []byte{0x83, 0x70, 0x74, 0x72}
	qdfFieldHdr_tail_5     = []byte{0x84, 0x74, 0x61, 0x69, 0x6c}
	qdfFieldHdr_id_18      = []byte{0x82, 0x69, 0x64}
	qdfFieldHdr_data_19    = []byte{0x84, 0x64, 0x61, 0x74, 0x61}
	qdfFieldHdr_rows_21    = []byte{0x84, 0x72, 0x6f, 0x77, 0x73}
	qdfFieldHdr_ts_40      = []byte{0x82, 0x74, 0x73}
	qdfFieldHdr_level_41   = []byte{0x85, 0x6c, 0x65, 0x76, 0x65, 0x6c}
	qdfFieldHdr_code_42    = []byte{0x84, 0x63, 0x6f, 0x64, 0x65}
	qdfFieldHdr_msg_43     = []byte{0x83, 0x6d, 0x73, 0x67}
	qdfFieldHdr_source_49  = []byte{0x86, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65}
	qdfFieldHdr_events_50  = []byte{0x86, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73}
	qdfFieldHdr_m_73       = []byte{0x81, 0x6d}
	qdfFieldHdr_value_83   = []byte{0x85, 0x76, 0x61, 0x6c, 0x75, 0x65}
	qdfFieldHdr_count_84   = []byte{0x85, 0x63, 0x6f, 0x75, 0x6e, 0x74}
	qdfFieldHdr_ok_85      = []byte{0x82, 0x6f, 0x6b}
	qdfFieldHdr_ratio_86   = []byte{0x85, 0x72, 0x61, 0x74, 0x69, 0x6f}
	qdfFieldHdr_name_92    = []byte{0x84, 0x6e, 0x61, 0x6d, 0x65}
	qdfFieldHdr_metrics_93 = []byte{0x87, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73}
	qdfFieldHdr_first_113  = []byte{0x85, 0x66, 0x69, 0x72, 0x73, 0x74}
	qdfFieldHdr_last_114   = []byte{0x84, 0x6c, 0x61, 0x73, 0x74}
	qdfFieldHdr_names_117  = []byte{0x85, 0x6e, 0x61, 0x6d, 0x65, 0x73}
	qdfFieldHdr_label_134  = []byte{0x85, 0x6c, 0x61, 0x62, 0x65, 0x6c}
	qdfFieldHdr_n_135      = []byte{0x81, 0x6e}
	qdfFieldHdr_a_137      = []byte{0x81, 0x61}
	qdfFieldHdr_b_138      = []byte{0x81, 0x62}
	qdfFieldHdr_c_139      = []byte{0x81, 0x63}
	qdfFieldHdr_d_140      = []byte{0x81, 0x64}
	qdfFieldHdr_inner_185  = []byte{0x85, 0x69, 0x6e, 0x6e, 0x65, 0x72}
	qdfFieldHdr_tags_186   = []byte{0x84, 0x74, 0x61, 0x67, 0x73}
	qdfFieldHdr_x_197      = []byte{0x81, 0x78}
	qdfFieldHdr_y_198      = []byte{0x81, 0x79}
	qdfFieldHdr_note_222   = []byte{0x84, 0x6e, 0x6f, 0x74, 0x65}
	qdfFieldHdr_age_248    = []byte{0x83, 0x61, 0x67, 0x65}
	qdfFieldHdr_active_249 = []byte{0x86, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65}
	qdfFieldHdr_score_250  = []byte{0x85, 0x73, 0x63, 0x6f, 0x72, 0x65}
	qdfFieldHdr_meta_251   = []byte{0x84, 0x6d, 0x65, 0x74, 0x61}
	qdfFieldHdr_when_252   = []byte{0x84, 0x77, 0x68, 0x65, 0x6e}
	qdfFieldHdr_buf_253    = []byte{0x83, 0x62, 0x75, 0x66}
	qdfFieldHdr_opt_254    = []byte{0x83, 0x6f, 0x70, 0x74}
	qdfFieldHdr_counts_255 = []byte{0x86, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73}
)

// Columnar shape descriptors: per element-type column names and kind
// bytes for the monomorphized tagColStruct transpose path.
var qdfColNames_GenBlobRow = []string{"id", "data"}
var qdfColKinds_GenBlobRow = []byte{0x00, 0x84}
var qdfColNames_GenEvent = []string{"ts", "level", "code", "msg"}
var qdfColKinds_GenEvent = []byte{0x05, 0x04, 0x00, 0x04}
var qdfColNames_GenMetric = []string{"ts", "value", "count", "ok", "ratio"}
var qdfColKinds_GenMetric = []byte{0x00, 0x02, 0x01, 0x03, 0x06}
var qdfColNames_GenName = []string{"first", "last"}
var qdfColKinds_GenName = []byte{0x04, 0x04}
var qdfColNames_GenOpt = []string{"a", "b", "c", "d"}
var qdfColKinds_GenOpt = []byte{0x80, 0x84, 0x83, 0x82}
var qdfHybNames_GenRow = []string{"id", "name", "inner", "tags"}
var qdfHybKinds_GenRow = []byte{0x00, 0x04, 0xff, 0xff}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *Edge) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_Edge byte
var qdfFieldHdrs_Edge = [][]byte{qdfFieldHdr_base_a_1, qdfFieldHdr_base_b_2, qdfFieldHdr_labels_3, qdfFieldHdr_ptr_4, qdfFieldHdr_tail_5}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *Edge) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_Edge, qdfFieldHdrs_Edge)
	e.WriteInt(int64(v.EmbeddedBase.BaseA))
	e.WriteString(string(v.EmbeddedBase.BaseB))
	if v.Labels == nil {
		e.WriteNil()
	} else {
		e.WriteMapHeader(len(v.Labels))
		if e.Canonical() {
			ks8 := make([]Label, 0, len(v.Labels))
			for k6 := range v.Labels {
				ks8 = append(ks8, k6)
			}
			slices.Sort(ks8)
			for _, k6 := range ks8 {
				vv7 := v.Labels[k6]
				e.WriteString(string(k6))
				e.WriteInt(int64(vv7))
			}
		} else {
			for k6, vv7 := range v.Labels {
				e.WriteString(string(k6))
				e.WriteInt(int64(vv7))
			}
		}
	}
	if v.Ptr == nil {
		e.WriteNil()
	} else {
		e.WriteString(string((*v.Ptr)))
	}
	e.WriteInt(int64(v.Tail))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *Edge) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *Edge) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "base_a":
		{
			rv9, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.EmbeddedBase.BaseA = int(rv9)
		}
	case "base_b":
		{
			rv10, err := d.ReadString()
			if err != nil {
				return err
			}
			v.EmbeddedBase.BaseB = rv10
		}
	case "labels":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Labels = nil
			} else {
				n11, err := d.ReadMapHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n11, 1); err != nil {
					return err
				}
				v.Labels = make(map[Label]int, n11)
				for range n11 {
					var k12 Label
					var vv13 int
					kb14, err := d.ReadStringBytes()
					if err != nil {
						return err
					}
					k12 = Label(d.InternKey(kb14))
					{
						rv15, err := d.ReadInt()
						if err != nil {
							return err
						}
						vv13 = int(rv15)
					}
					v.Labels[k12] = vv13
				}
			}
		}
	case "ptr":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Ptr = nil
			} else {
				v.Ptr = new(Label)
				{
					nv16, err := d.ReadString()
					if err != nil {
						return err
					}
					(*v.Ptr) = Label(nv16)
				}
			}
		}
	case "tail":
		{
			rv17, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.Tail = int(rv17)
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *Edge) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *Edge) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *Edge) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenBlobRow) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenBlobRow byte
var qdfFieldHdrs_GenBlobRow = [][]byte{qdfFieldHdr_id_18, qdfFieldHdr_data_19}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenBlobRow) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenBlobRow, qdfFieldHdrs_GenBlobRow)
	e.WriteInt(int64(v.ID))
	if v.Data == nil {
		e.WriteNil()
	} else {
		e.WriteBytes([]byte(v.Data))
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenBlobRow) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenBlobRow) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "id":
		{
			rv20, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.ID = int64(rv20)
		}
	case "data":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Data = nil
			} else {
				_v, err := d.ReadBytes()
				if err != nil {
					return err
				}
				v.Data = _v
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenBlobRow) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenBlobRow) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenBlobRow) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenBlobSet) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenBlobSet byte
var qdfFieldHdrs_GenBlobSet = [][]byte{qdfFieldHdr_rows_21}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenBlobSet) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenBlobSet, qdfFieldHdrs_GenBlobSet)
	if v.Rows == nil {
		e.WriteNil()
	} else if len(v.Rows) >= 16 { // columnarMinElems
		col22 := v.Rows
		e.WriteColStructHeader(len(col22), qdfColNames_GenBlobRow, qdfColKinds_GenBlobRow)
		c23 := e.ScratchInt(len(col22))
		for i := range col22 {
			c23[i] = int64(col22[i].ID)
		}
		if err := e.WriteIntColumn(c23); err != nil {
			return err
		}
		mask24 := e.ScratchMask(len(col22))
		c26 := e.ScratchString(len(col22))
		di25 := 0
		for i := range col22 {
			if col22[i].Data != nil {
				mask24[i>>3] |= 1 << uint(i&7)
				c26[di25] = unsafe.String(unsafe.SliceData(col22[i].Data), len(col22[i].Data))
				di25++
			}
		}
		e.WriteColNullMask(mask24)
		e.WriteStringColumn(c26[:di25])
	} else {
		e.WriteArrayHeader(len(v.Rows))
		for i27 := range v.Rows {
			if err := qdf.EncodeNested(e, &v.Rows[i27]); err != nil {
				return err
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenBlobSet) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenBlobSet) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "rows":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Rows = nil
			} else if d.PeekColStruct() {
				n28, names29, kinds30, err := d.ReadColStructHeader()
				if err != nil {
					return err
				}
				if err := qdf.CheckColumnarBytes(n28, unsafe.Sizeof(*new(GenBlobRow))); err != nil {
					return err
				}
				v.Rows = make([]GenBlobRow, n28)
				for ci31 := range names29 {
					switch names29[ci31] {
					case "id":
						if kinds30[ci31] != 0x00 {
							return qdf.ErrTypeMismatch
						}
						col32, err := d.ReadIntColumn(n28)
						if err != nil {
							return err
						}
						for i := range col32 {
							v.Rows[i].ID = int64(col32[i])
						}
					case "data":
						if kinds30[ci31] != 0x84 {
							return qdf.ErrTypeMismatch
						}
						mask33, present34, err := d.ReadColNullMask(n28)
						if err != nil {
							return err
						}
						col35, err := d.ReadStringColumn(present34)
						if err != nil {
							return err
						}
						di36 := 0
						for i := range v.Rows {
							if mask33[i>>3]&(1<<uint(i&7)) != 0 {
								v.Rows[i].Data = []byte([]byte(col35[di36]))
								di36++
							} else {
								v.Rows[i].Data = nil
							}
						}
					default:
						return qdf.ErrTypeMismatch
					}
				}
				d.ClearColMaxLen()
			} else {
				n38, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n38, 1); err != nil {
					return err
				}
				v.Rows = make([]GenBlobRow, n38)
				for i39 := range n38 {
					if err := qdf.DecodeNested(d, &v.Rows[i39]); err != nil {
						return err
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenBlobSet) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenBlobSet) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenBlobSet) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenEvent) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenEvent byte
var qdfFieldHdrs_GenEvent = [][]byte{qdfFieldHdr_ts_40, qdfFieldHdr_level_41, qdfFieldHdr_code_42, qdfFieldHdr_msg_43}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenEvent) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenEvent, qdfFieldHdrs_GenEvent)
	{
		_t := (v.TS).UTC()
		e.WriteTimestamp(_t.Unix(), uint32(_t.Nanosecond()))
	}
	e.WriteString(string(v.Level))
	e.WriteInt(int64(v.Code))
	e.WriteString(string(v.Msg))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenEvent) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenEvent) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "ts":
		{
			sec44, nsec45, err := d.ReadTimestamp()
			if err != nil {
				return err
			}
			v.TS = time.Unix(sec44, int64(nsec45)).UTC()
		}
	case "level":
		{
			rv46, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Level = rv46
		}
	case "code":
		{
			rv47, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.Code = int32(rv47)
		}
	case "msg":
		{
			rv48, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Msg = rv48
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenEvent) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenEvent) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenEvent) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenEventLog) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenEventLog byte
var qdfFieldHdrs_GenEventLog = [][]byte{qdfFieldHdr_source_49, qdfFieldHdr_events_50}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenEventLog) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenEventLog, qdfFieldHdrs_GenEventLog)
	e.WriteString(string(v.Source))
	if v.Events == nil {
		e.WriteNil()
	} else if len(v.Events) >= 16 { // columnarMinElems
		col51 := v.Events
		e.WriteColStructHeader(len(col51), qdfColNames_GenEvent, qdfColKinds_GenEvent)
		sec53 := e.ScratchInt(len(col51))
		ns54 := e.ScratchUint(len(col51))
		for i := range col51 {
			t55 := col51[i].TS.UTC()
			sec53[i] = t55.Unix()
			ns54[i] = uint64(t55.Nanosecond())
		}
		if err := e.WriteTimeColumn(sec53, ns54); err != nil {
			return err
		}
		c56 := e.ScratchString(len(col51))
		for i := range col51 {
			c56[i] = string(col51[i].Level)
		}
		e.WriteStringColumn(c56)
		c57 := e.ScratchInt(len(col51))
		for i := range col51 {
			c57[i] = int64(col51[i].Code)
		}
		if err := e.WriteIntColumn(c57); err != nil {
			return err
		}
		c58 := e.ScratchString(len(col51))
		for i := range col51 {
			c58[i] = string(col51[i].Msg)
		}
		e.WriteStringColumn(c58)
	} else {
		e.WriteArrayHeader(len(v.Events))
		for i59 := range v.Events {
			if err := qdf.EncodeNested(e, &v.Events[i59]); err != nil {
				return err
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenEventLog) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenEventLog) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "source":
		{
			rv60, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Source = rv60
		}
	case "events":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Events = nil
			} else if d.PeekColStruct() {
				n61, names62, kinds63, err := d.ReadColStructHeader()
				if err != nil {
					return err
				}
				if err := qdf.CheckColumnarBytes(n61, unsafe.Sizeof(*new(GenEvent))); err != nil {
					return err
				}
				v.Events = make([]GenEvent, n61)
				for ci64 := range names62 {
					switch names62[ci64] {
					case "ts":
						if kinds63[ci64] != 0x05 {
							return qdf.ErrTypeMismatch
						}
						sec66, ns67, err := d.ReadTimeColumn(n61)
						if err != nil {
							return err
						}
						for i := range sec66 {
							v.Events[i].TS = time.Unix(sec66[i], int64(ns67[i])).UTC()
						}
					case "level":
						if kinds63[ci64] != 0x04 {
							return qdf.ErrTypeMismatch
						}
						col68, err := d.ReadStringColumn(n61)
						if err != nil {
							return err
						}
						for i := range col68 {
							v.Events[i].Level = string(col68[i])
						}
					case "code":
						if kinds63[ci64] != 0x00 {
							return qdf.ErrTypeMismatch
						}
						col69, err := d.ReadIntColumn(n61)
						if err != nil {
							return err
						}
						for i := range col69 {
							v.Events[i].Code = int32(col69[i])
						}
					case "msg":
						if kinds63[ci64] != 0x04 {
							return qdf.ErrTypeMismatch
						}
						col70, err := d.ReadStringColumn(n61)
						if err != nil {
							return err
						}
						for i := range col70 {
							v.Events[i].Msg = string(col70[i])
						}
					default:
						return qdf.ErrTypeMismatch
					}
				}
				d.ClearColMaxLen()
			} else {
				n71, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n71, 1); err != nil {
					return err
				}
				v.Events = make([]GenEvent, n71)
				for i72 := range n71 {
					if err := qdf.DecodeNested(d, &v.Events[i72]); err != nil {
						return err
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenEventLog) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenEventLog) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenEventLog) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenFloatMap) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenFloatMap byte
var qdfFieldHdrs_GenFloatMap = [][]byte{qdfFieldHdr_m_73}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenFloatMap) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenFloatMap, qdfFieldHdrs_GenFloatMap)
	if v.M == nil {
		e.WriteNil()
	} else {
		e.WriteMapHeader(len(v.M))
		if e.Canonical() {
			ps76 := make([]struct {
				k float64
				v string
			}, 0, len(v.M))
			for k74, vv75 := range v.M {
				ps76 = append(ps76, struct {
					k float64
					v string
				}{k74, vv75})
			}
			slices.SortFunc(ps76, func(a, b struct {
				k float64
				v string
			}) int { return cmp.Compare(math.Float64bits(float64(a.k)), math.Float64bits(float64(b.k))) })
			for _, p77 := range ps76 {
				k74 := p77.k
				vv75 := p77.v
				e.WriteFloat64(float64(k74))
				e.WriteString(string(vv75))
			}
		} else {
			for k74, vv75 := range v.M {
				e.WriteFloat64(float64(k74))
				e.WriteString(string(vv75))
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenFloatMap) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenFloatMap) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "m":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.M = nil
			} else {
				n78, err := d.ReadMapHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n78, 1); err != nil {
					return err
				}
				v.M = make(map[float64]string, n78)
				for range n78 {
					var k79 float64
					var vv80 string
					{
						rv81, err := d.ReadFloat64()
						if err != nil {
							return err
						}
						k79 = rv81
					}
					{
						rv82, err := d.ReadString()
						if err != nil {
							return err
						}
						vv80 = rv82
					}
					v.M[k79] = vv80
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenFloatMap) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenFloatMap) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenFloatMap) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenMetric) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenMetric byte
var qdfFieldHdrs_GenMetric = [][]byte{qdfFieldHdr_ts_40, qdfFieldHdr_value_83, qdfFieldHdr_count_84, qdfFieldHdr_ok_85, qdfFieldHdr_ratio_86}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenMetric) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenMetric, qdfFieldHdrs_GenMetric)
	e.WriteInt(int64(v.TS))
	e.WriteFloat64(float64(v.Value))
	e.WriteUint(uint64(v.Count))
	e.WriteBool(bool(v.OK))
	e.WriteFloat32(float32(v.Ratio))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenMetric) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenMetric) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "ts":
		{
			rv87, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.TS = int64(rv87)
		}
	case "value":
		{
			rv88, err := d.ReadFloat64()
			if err != nil {
				return err
			}
			v.Value = rv88
		}
	case "count":
		{
			rv89, err := d.ReadUint()
			if err != nil {
				return err
			}
			v.Count = uint32(rv89)
		}
	case "ok":
		{
			rv90, err := d.ReadBool()
			if err != nil {
				return err
			}
			v.OK = rv90
		}
	case "ratio":
		{
			rv91, err := d.ReadFloat32()
			if err != nil {
				return err
			}
			v.Ratio = rv91
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenMetric) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenMetric) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenMetric) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenMetricBatch) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenMetricBatch byte
var qdfFieldHdrs_GenMetricBatch = [][]byte{qdfFieldHdr_name_92, qdfFieldHdr_metrics_93}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenMetricBatch) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenMetricBatch, qdfFieldHdrs_GenMetricBatch)
	e.WriteString(string(v.Name))
	if v.Metrics == nil {
		e.WriteNil()
	} else if len(v.Metrics) >= 16 { // columnarMinElems
		col94 := v.Metrics
		e.WriteColStructHeader(len(col94), qdfColNames_GenMetric, qdfColKinds_GenMetric)
		c95 := e.ScratchInt(len(col94))
		for i := range col94 {
			c95[i] = int64(col94[i].TS)
		}
		if err := e.WriteIntColumn(c95); err != nil {
			return err
		}
		c96 := e.ScratchFloat64(len(col94))
		for i := range col94 {
			c96[i] = float64(col94[i].Value)
		}
		if err := e.WriteFloat64Column(c96); err != nil {
			return err
		}
		c97 := e.ScratchUint(len(col94))
		for i := range col94 {
			c97[i] = uint64(col94[i].Count)
		}
		if err := e.WriteUintColumn(c97); err != nil {
			return err
		}
		c98 := e.ScratchBool(len(col94))
		for i := range col94 {
			c98[i] = col94[i].OK
		}
		if err := e.WriteBoolColumn(c98); err != nil {
			return err
		}
		c99 := e.ScratchFloat32(len(col94))
		for i := range col94 {
			c99[i] = float32(col94[i].Ratio)
		}
		if err := e.WriteFloat32Column(c99); err != nil {
			return err
		}
	} else {
		e.WriteArrayHeader(len(v.Metrics))
		for i100 := range v.Metrics {
			if err := qdf.EncodeNested(e, &v.Metrics[i100]); err != nil {
				return err
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenMetricBatch) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenMetricBatch) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "name":
		{
			rv101, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Name = rv101
		}
	case "metrics":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Metrics = nil
			} else if d.PeekColStruct() {
				n102, names103, kinds104, err := d.ReadColStructHeader()
				if err != nil {
					return err
				}
				if err := qdf.CheckColumnarBytes(n102, unsafe.Sizeof(*new(GenMetric))); err != nil {
					return err
				}
				v.Metrics = make([]GenMetric, n102)
				for ci105 := range names103 {
					switch names103[ci105] {
					case "ts":
						if kinds104[ci105] != 0x00 {
							return qdf.ErrTypeMismatch
						}
						col106, err := d.ReadIntColumn(n102)
						if err != nil {
							return err
						}
						for i := range col106 {
							v.Metrics[i].TS = int64(col106[i])
						}
					case "value":
						if kinds104[ci105] != 0x02 {
							return qdf.ErrTypeMismatch
						}
						col107, err := d.ReadFloat64Column(n102)
						if err != nil {
							return err
						}
						for i := range col107 {
							v.Metrics[i].Value = float64(col107[i])
						}
					case "count":
						if kinds104[ci105] != 0x01 {
							return qdf.ErrTypeMismatch
						}
						col108, err := d.ReadUintColumn(n102)
						if err != nil {
							return err
						}
						for i := range col108 {
							v.Metrics[i].Count = uint32(col108[i])
						}
					case "ok":
						if kinds104[ci105] != 0x03 {
							return qdf.ErrTypeMismatch
						}
						col109, err := d.ReadBoolColumn(n102)
						if err != nil {
							return err
						}
						for i := range col109 {
							v.Metrics[i].OK = col109[i]
						}
					case "ratio":
						if kinds104[ci105] != 0x06 {
							return qdf.ErrTypeMismatch
						}
						col110, err := d.ReadFloat32Column(n102)
						if err != nil {
							return err
						}
						for i := range col110 {
							v.Metrics[i].Ratio = float32(col110[i])
						}
					default:
						return qdf.ErrTypeMismatch
					}
				}
				d.ClearColMaxLen()
			} else {
				n111, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n111, 1); err != nil {
					return err
				}
				v.Metrics = make([]GenMetric, n111)
				for i112 := range n111 {
					if err := qdf.DecodeNested(d, &v.Metrics[i112]); err != nil {
						return err
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenMetricBatch) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenMetricBatch) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenMetricBatch) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenName) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenName byte
var qdfFieldHdrs_GenName = [][]byte{qdfFieldHdr_first_113, qdfFieldHdr_last_114}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenName) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenName, qdfFieldHdrs_GenName)
	e.WriteString(string(v.First))
	e.WriteString(string(v.Last))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenName) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenName) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "first":
		{
			rv115, err := d.ReadString()
			if err != nil {
				return err
			}
			v.First = rv115
		}
	case "last":
		{
			rv116, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Last = rv116
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenName) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenName) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenName) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenNameList) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenNameList byte
var qdfFieldHdrs_GenNameList = [][]byte{qdfFieldHdr_names_117}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenNameList) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenNameList, qdfFieldHdrs_GenNameList)
	if v.Names == nil {
		e.WriteNil()
	} else if len(v.Names) >= 16 { // columnarMinElems
		col118 := v.Names
		pb120 := make([]string, min(len(col118), 32))
		for i := range pb120 {
			pb120[i] = string(col118[i].First)
		}
		pb121 := make([]string, min(len(col118), 32))
		for i := range pb121 {
			pb121[i] = string(col118[i].Last)
		}
		ben119 := qdf.StringColumnsBeneficial(pb120, pb121)
		if ben119 {
			e.WriteColStructHeader(len(col118), qdfColNames_GenName, qdfColKinds_GenName)
			c122 := e.ScratchString(len(col118))
			for i := range col118 {
				c122[i] = string(col118[i].First)
			}
			e.WriteStringColumn(c122)
			c123 := e.ScratchString(len(col118))
			for i := range col118 {
				c123[i] = string(col118[i].Last)
			}
			e.WriteStringColumn(c123)
		} else {
			e.WriteArrayHeader(len(col118))
			for i124 := range col118 {
				if err := qdf.EncodeNested(e, &col118[i124]); err != nil {
					return err
				}
			}
		}
	} else {
		e.WriteArrayHeader(len(v.Names))
		for i125 := range v.Names {
			if err := qdf.EncodeNested(e, &v.Names[i125]); err != nil {
				return err
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenNameList) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenNameList) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "names":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Names = nil
			} else if d.PeekColStruct() {
				n126, names127, kinds128, err := d.ReadColStructHeader()
				if err != nil {
					return err
				}
				if err := qdf.CheckColumnarBytes(n126, unsafe.Sizeof(*new(GenName))); err != nil {
					return err
				}
				v.Names = make([]GenName, n126)
				for ci129 := range names127 {
					switch names127[ci129] {
					case "first":
						if kinds128[ci129] != 0x04 {
							return qdf.ErrTypeMismatch
						}
						col130, err := d.ReadStringColumn(n126)
						if err != nil {
							return err
						}
						for i := range col130 {
							v.Names[i].First = string(col130[i])
						}
					case "last":
						if kinds128[ci129] != 0x04 {
							return qdf.ErrTypeMismatch
						}
						col131, err := d.ReadStringColumn(n126)
						if err != nil {
							return err
						}
						for i := range col131 {
							v.Names[i].Last = string(col131[i])
						}
					default:
						return qdf.ErrTypeMismatch
					}
				}
				d.ClearColMaxLen()
			} else {
				n132, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n132, 1); err != nil {
					return err
				}
				v.Names = make([]GenName, n132)
				for i133 := range n132 {
					if err := qdf.DecodeNested(d, &v.Names[i133]); err != nil {
						return err
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenNameList) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenNameList) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenNameList) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenNamedCodec) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenNamedCodec byte
var qdfFieldHdrs_GenNamedCodec = [][]byte{qdfFieldHdr_label_134, qdfFieldHdr_n_135}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenNamedCodec) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenNamedCodec, qdfFieldHdrs_GenNamedCodec)
	if err := qdf.EncodeNested(e, &v.Label); err != nil {
		return err
	}
	e.WriteInt(int64(v.N))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenNamedCodec) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenNamedCodec) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "label":
		if err := qdf.DecodeNested(d, &v.Label); err != nil {
			return err
		}
	case "n":
		{
			rv136, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.N = int64(rv136)
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenNamedCodec) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenNamedCodec) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenNamedCodec) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenOpt) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenOpt byte
var qdfFieldHdrs_GenOpt = [][]byte{qdfFieldHdr_a_137, qdfFieldHdr_b_138, qdfFieldHdr_c_139, qdfFieldHdr_d_140}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenOpt) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenOpt, qdfFieldHdrs_GenOpt)
	if v.A == nil {
		e.WriteNil()
	} else {
		e.WriteInt(int64((*v.A)))
	}
	if v.B == nil {
		e.WriteNil()
	} else {
		e.WriteString(string((*v.B)))
	}
	if v.C == nil {
		e.WriteNil()
	} else {
		e.WriteBool(bool((*v.C)))
	}
	if v.D == nil {
		e.WriteNil()
	} else {
		e.WriteFloat64(float64((*v.D)))
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenOpt) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenOpt) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "a":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.A = nil
			} else {
				v.A = new(int32)
				{
					rv141, err := d.ReadInt()
					if err != nil {
						return err
					}
					(*v.A) = int32(rv141)
				}
			}
		}
	case "b":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.B = nil
			} else {
				v.B = new(string)
				{
					rv142, err := d.ReadString()
					if err != nil {
						return err
					}
					(*v.B) = rv142
				}
			}
		}
	case "c":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.C = nil
			} else {
				v.C = new(bool)
				{
					rv143, err := d.ReadBool()
					if err != nil {
						return err
					}
					(*v.C) = rv143
				}
			}
		}
	case "d":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.D = nil
			} else {
				v.D = new(float64)
				{
					rv144, err := d.ReadFloat64()
					if err != nil {
						return err
					}
					(*v.D) = rv144
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenOpt) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenOpt) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenOpt) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenOptSet) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenOptSet byte
var qdfFieldHdrs_GenOptSet = [][]byte{qdfFieldHdr_rows_21}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenOptSet) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenOptSet, qdfFieldHdrs_GenOptSet)
	if v.Rows == nil {
		e.WriteNil()
	} else if len(v.Rows) >= 16 { // columnarMinElems
		col145 := v.Rows
		e.WriteColStructHeader(len(col145), qdfColNames_GenOpt, qdfColKinds_GenOpt)
		mask146 := e.ScratchMask(len(col145))
		c148 := e.ScratchInt(len(col145))
		di147 := 0
		for i := range col145 {
			if col145[i].A != nil {
				mask146[i>>3] |= 1 << uint(i&7)
				c148[di147] = int64(*col145[i].A)
				di147++
			}
		}
		e.WriteColNullMask(mask146)
		if err := e.WriteIntColumn(c148[:di147]); err != nil {
			return err
		}
		mask149 := e.ScratchMask(len(col145))
		c151 := e.ScratchString(len(col145))
		di150 := 0
		for i := range col145 {
			if col145[i].B != nil {
				mask149[i>>3] |= 1 << uint(i&7)
				c151[di150] = string(*col145[i].B)
				di150++
			}
		}
		e.WriteColNullMask(mask149)
		e.WriteStringColumn(c151[:di150])
		mask152 := e.ScratchMask(len(col145))
		c154 := e.ScratchBool(len(col145))
		di153 := 0
		for i := range col145 {
			if col145[i].C != nil {
				mask152[i>>3] |= 1 << uint(i&7)
				c154[di153] = *col145[i].C
				di153++
			}
		}
		e.WriteColNullMask(mask152)
		if err := e.WriteBoolColumn(c154[:di153]); err != nil {
			return err
		}
		mask155 := e.ScratchMask(len(col145))
		c157 := e.ScratchFloat64(len(col145))
		di156 := 0
		for i := range col145 {
			if col145[i].D != nil {
				mask155[i>>3] |= 1 << uint(i&7)
				c157[di156] = float64(*col145[i].D)
				di156++
			}
		}
		e.WriteColNullMask(mask155)
		if err := e.WriteFloat64Column(c157[:di156]); err != nil {
			return err
		}
	} else {
		e.WriteArrayHeader(len(v.Rows))
		for i158 := range v.Rows {
			if err := qdf.EncodeNested(e, &v.Rows[i158]); err != nil {
				return err
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenOptSet) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenOptSet) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "rows":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Rows = nil
			} else if d.PeekColStruct() {
				n159, names160, kinds161, err := d.ReadColStructHeader()
				if err != nil {
					return err
				}
				if err := qdf.CheckColumnarBytes(n159, unsafe.Sizeof(*new(GenOpt))); err != nil {
					return err
				}
				v.Rows = make([]GenOpt, n159)
				for ci162 := range names160 {
					switch names160[ci162] {
					case "a":
						if kinds161[ci162] != 0x80 {
							return qdf.ErrTypeMismatch
						}
						mask163, present164, err := d.ReadColNullMask(n159)
						if err != nil {
							return err
						}
						col165, err := d.ReadIntColumn(present164)
						if err != nil {
							return err
						}
						di166 := 0
						for i := range v.Rows {
							if mask163[i>>3]&(1<<uint(i&7)) != 0 {
								v167 := int32(col165[di166])
								v.Rows[i].A = &v167
								di166++
							} else {
								v.Rows[i].A = nil
							}
						}
					case "b":
						if kinds161[ci162] != 0x84 {
							return qdf.ErrTypeMismatch
						}
						mask168, present169, err := d.ReadColNullMask(n159)
						if err != nil {
							return err
						}
						col170, err := d.ReadStringColumn(present169)
						if err != nil {
							return err
						}
						di171 := 0
						for i := range v.Rows {
							if mask168[i>>3]&(1<<uint(i&7)) != 0 {
								v172 := string(col170[di171])
								v.Rows[i].B = &v172
								di171++
							} else {
								v.Rows[i].B = nil
							}
						}
					case "c":
						if kinds161[ci162] != 0x83 {
							return qdf.ErrTypeMismatch
						}
						mask173, present174, err := d.ReadColNullMask(n159)
						if err != nil {
							return err
						}
						col175, err := d.ReadBoolColumn(present174)
						if err != nil {
							return err
						}
						di176 := 0
						for i := range v.Rows {
							if mask173[i>>3]&(1<<uint(i&7)) != 0 {
								v177 := col175[di176]
								v.Rows[i].C = &v177
								di176++
							} else {
								v.Rows[i].C = nil
							}
						}
					case "d":
						if kinds161[ci162] != 0x82 {
							return qdf.ErrTypeMismatch
						}
						mask178, present179, err := d.ReadColNullMask(n159)
						if err != nil {
							return err
						}
						col180, err := d.ReadFloat64Column(present179)
						if err != nil {
							return err
						}
						di181 := 0
						for i := range v.Rows {
							if mask178[i>>3]&(1<<uint(i&7)) != 0 {
								v182 := float64(col180[di181])
								v.Rows[i].D = &v182
								di181++
							} else {
								v.Rows[i].D = nil
							}
						}
					default:
						return qdf.ErrTypeMismatch
					}
				}
				d.ClearColMaxLen()
			} else {
				n183, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n183, 1); err != nil {
					return err
				}
				v.Rows = make([]GenOpt, n183)
				for i184 := range n183 {
					if err := qdf.DecodeNested(d, &v.Rows[i184]); err != nil {
						return err
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenOptSet) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenOptSet) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenOptSet) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenRow) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenRow byte
var qdfFieldHdrs_GenRow = [][]byte{qdfFieldHdr_id_18, qdfFieldHdr_name_92, qdfFieldHdr_inner_185, qdfFieldHdr_tags_186}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenRow) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenRow, qdfFieldHdrs_GenRow)
	e.WriteInt(int64(v.ID))
	e.WriteString(string(v.Name))
	if err := qdf.EncodeNested(e, &v.Inner); err != nil {
		return err
	}
	if v.Tags == nil {
		e.WriteNil()
	} else {
		e.WriteMapHeader(len(v.Tags))
		if e.Canonical() {
			ks189 := make([]string, 0, len(v.Tags))
			for k187 := range v.Tags {
				ks189 = append(ks189, k187)
			}
			slices.Sort(ks189)
			for _, k187 := range ks189 {
				vv188 := v.Tags[k187]
				e.WriteString(string(k187))
				e.WriteInt(int64(vv188))
			}
		} else {
			for k187, vv188 := range v.Tags {
				e.WriteString(string(k187))
				e.WriteInt(int64(vv188))
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenRow) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenRow) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "id":
		{
			rv190, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.ID = int64(rv190)
		}
	case "name":
		{
			rv191, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Name = rv191
		}
	case "inner":
		if err := qdf.DecodeNested(d, &v.Inner); err != nil {
			return err
		}
	case "tags":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Tags = nil
			} else {
				n192, err := d.ReadMapHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n192, 1); err != nil {
					return err
				}
				v.Tags = make(map[string]int, n192)
				for range n192 {
					var k193 string
					var vv194 int
					kb195, err := d.ReadStringBytes()
					if err != nil {
						return err
					}
					k193 = string(d.InternKey(kb195))
					{
						rv196, err := d.ReadInt()
						if err != nil {
							return err
						}
						vv194 = int(rv196)
					}
					v.Tags[k193] = vv194
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenRow) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenRow) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenRow) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenRowInner) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenRowInner byte
var qdfFieldHdrs_GenRowInner = [][]byte{qdfFieldHdr_x_197, qdfFieldHdr_y_198}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenRowInner) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenRowInner, qdfFieldHdrs_GenRowInner)
	e.WriteInt(int64(v.X))
	e.WriteString(string(v.Y))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenRowInner) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenRowInner) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "x":
		{
			rv199, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.X = int(rv199)
		}
	case "y":
		{
			rv200, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Y = rv200
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenRowInner) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenRowInner) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenRowInner) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenRowSet) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenRowSet byte
var qdfFieldHdrs_GenRowSet = [][]byte{qdfFieldHdr_rows_21}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenRowSet) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenRowSet, qdfFieldHdrs_GenRowSet)
	if v.Rows == nil {
		e.WriteNil()
	} else if len(v.Rows) >= 16 { // columnarMinElems
		col201 := v.Rows
		e.WriteHybridColStructHeader(len(col201), qdfHybNames_GenRow, qdfHybKinds_GenRow)
		c202 := e.ScratchInt(len(col201))
		for i := range col201 {
			c202[i] = int64(col201[i].ID)
		}
		if err := e.WriteIntColumn(c202); err != nil {
			return err
		}
		c203 := e.ScratchString(len(col201))
		for i := range col201 {
			c203[i] = string(col201[i].Name)
		}
		e.WriteStringColumn(c203)
		for i204 := range col201 {
			if err := qdf.EncodeNested(e, &col201[i204].Inner); err != nil {
				return err
			}
			if col201[i204].Tags == nil {
				e.WriteNil()
			} else {
				e.WriteMapHeader(len(col201[i204].Tags))
				if e.Canonical() {
					ks207 := make([]string, 0, len(col201[i204].Tags))
					for k205 := range col201[i204].Tags {
						ks207 = append(ks207, k205)
					}
					slices.Sort(ks207)
					for _, k205 := range ks207 {
						vv206 := col201[i204].Tags[k205]
						e.WriteString(string(k205))
						e.WriteInt(int64(vv206))
					}
				} else {
					for k205, vv206 := range col201[i204].Tags {
						e.WriteString(string(k205))
						e.WriteInt(int64(vv206))
					}
				}
			}
		}
	} else {
		e.WriteArrayHeader(len(v.Rows))
		for i208 := range v.Rows {
			if err := qdf.EncodeNested(e, &v.Rows[i208]); err != nil {
				return err
			}
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenRowSet) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenRowSet) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "rows":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Rows = nil
			} else if d.PeekHybridColStruct() {
				n209, names210, kinds211, err := d.ReadHybridColStructHeader()
				if err != nil {
					return err
				}
				if !slices.Equal(names210, qdfHybNames_GenRow) || !slices.Equal(kinds211, qdfHybKinds_GenRow) {
					return qdf.ErrTypeMismatch
				}
				if err := qdf.CheckColumnarBytes(n209, unsafe.Sizeof(*new(GenRow))); err != nil {
					return err
				}
				v.Rows = make([]GenRow, n209)
				col212, err := d.ReadIntColumn(n209)
				if err != nil {
					return err
				}
				for i := range col212 {
					v.Rows[i].ID = int64(col212[i])
				}
				col213, err := d.ReadStringColumn(n209)
				if err != nil {
					return err
				}
				for i := range col213 {
					v.Rows[i].Name = string(col213[i])
				}
				d.ClearColMaxLen()
				for i214 := range v.Rows {
					if err := qdf.DecodeNested(d, &v.Rows[i214].Inner); err != nil {
						return err
					}
					{
						isNil, err := d.IsNil()
						if err != nil {
							return err
						}
						if isNil {
							v.Rows[i214].Tags = nil
						} else {
							n215, err := d.ReadMapHeader()
							if err != nil {
								return err
							}
							if err := d.CheckLength(n215, 1); err != nil {
								return err
							}
							v.Rows[i214].Tags = make(map[string]int, n215)
							for range n215 {
								var k216 string
								var vv217 int
								kb218, err := d.ReadStringBytes()
								if err != nil {
									return err
								}
								k216 = string(d.InternKey(kb218))
								{
									rv219, err := d.ReadInt()
									if err != nil {
										return err
									}
									vv217 = int(rv219)
								}
								v.Rows[i214].Tags[k216] = vv217
							}
						}
					}
				}
			} else {
				n220, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n220, 1); err != nil {
					return err
				}
				v.Rows = make([]GenRow, n220)
				for i221 := range n220 {
					if err := qdf.DecodeNested(d, &v.Rows[i221]); err != nil {
						return err
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenRowSet) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenRowSet) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenRowSet) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *GenTrailed) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_GenTrailed byte
var qdfFieldHdrs_GenTrailed = [][]byte{qdfFieldHdr_rows_21, qdfFieldHdr_note_222, qdfFieldHdr_tail_5}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *GenTrailed) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_GenTrailed, qdfFieldHdrs_GenTrailed)
	if v.Rows == nil {
		e.WriteNil()
	} else if len(v.Rows) >= 16 { // columnarMinElems
		col223 := v.Rows
		e.WriteColStructHeader(len(col223), qdfColNames_GenMetric, qdfColKinds_GenMetric)
		c224 := e.ScratchInt(len(col223))
		for i := range col223 {
			c224[i] = int64(col223[i].TS)
		}
		if err := e.WriteIntColumn(c224); err != nil {
			return err
		}
		c225 := e.ScratchFloat64(len(col223))
		for i := range col223 {
			c225[i] = float64(col223[i].Value)
		}
		if err := e.WriteFloat64Column(c225); err != nil {
			return err
		}
		c226 := e.ScratchUint(len(col223))
		for i := range col223 {
			c226[i] = uint64(col223[i].Count)
		}
		if err := e.WriteUintColumn(c226); err != nil {
			return err
		}
		c227 := e.ScratchBool(len(col223))
		for i := range col223 {
			c227[i] = col223[i].OK
		}
		if err := e.WriteBoolColumn(c227); err != nil {
			return err
		}
		c228 := e.ScratchFloat32(len(col223))
		for i := range col223 {
			c228[i] = float32(col223[i].Ratio)
		}
		if err := e.WriteFloat32Column(c228); err != nil {
			return err
		}
	} else {
		e.WriteArrayHeader(len(v.Rows))
		for i229 := range v.Rows {
			if err := qdf.EncodeNested(e, &v.Rows[i229]); err != nil {
				return err
			}
		}
	}
	e.WriteString(string(v.Note))
	if v.Tail == nil {
		e.WriteNil()
	} else {
		e.WriteArrayHeader(len(v.Tail))
		for i230 := range v.Tail {
			e.WriteInt(int64(v.Tail[i230]))
		}
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *GenTrailed) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *GenTrailed) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "rows":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Rows = nil
			} else if d.PeekColStruct() {
				n231, names232, kinds233, err := d.ReadColStructHeader()
				if err != nil {
					return err
				}
				if err := qdf.CheckColumnarBytes(n231, unsafe.Sizeof(*new(GenMetric))); err != nil {
					return err
				}
				v.Rows = make([]GenMetric, n231)
				for ci234 := range names232 {
					switch names232[ci234] {
					case "ts":
						if kinds233[ci234] != 0x00 {
							return qdf.ErrTypeMismatch
						}
						col235, err := d.ReadIntColumn(n231)
						if err != nil {
							return err
						}
						for i := range col235 {
							v.Rows[i].TS = int64(col235[i])
						}
					case "value":
						if kinds233[ci234] != 0x02 {
							return qdf.ErrTypeMismatch
						}
						col236, err := d.ReadFloat64Column(n231)
						if err != nil {
							return err
						}
						for i := range col236 {
							v.Rows[i].Value = float64(col236[i])
						}
					case "count":
						if kinds233[ci234] != 0x01 {
							return qdf.ErrTypeMismatch
						}
						col237, err := d.ReadUintColumn(n231)
						if err != nil {
							return err
						}
						for i := range col237 {
							v.Rows[i].Count = uint32(col237[i])
						}
					case "ok":
						if kinds233[ci234] != 0x03 {
							return qdf.ErrTypeMismatch
						}
						col238, err := d.ReadBoolColumn(n231)
						if err != nil {
							return err
						}
						for i := range col238 {
							v.Rows[i].OK = col238[i]
						}
					case "ratio":
						if kinds233[ci234] != 0x06 {
							return qdf.ErrTypeMismatch
						}
						col239, err := d.ReadFloat32Column(n231)
						if err != nil {
							return err
						}
						for i := range col239 {
							v.Rows[i].Ratio = float32(col239[i])
						}
					default:
						return qdf.ErrTypeMismatch
					}
				}
				d.ClearColMaxLen()
			} else {
				n240, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n240, 1); err != nil {
					return err
				}
				v.Rows = make([]GenMetric, n240)
				for i241 := range n240 {
					if err := qdf.DecodeNested(d, &v.Rows[i241]); err != nil {
						return err
					}
				}
			}
		}
	case "note":
		{
			rv242, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Note = rv242
		}
	case "tail":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Tail = nil
			} else {
				n243, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n243, 1); err != nil {
					return err
				}
				v.Tail = make([]int64, n243)
				for i244 := range n243 {
					{
						rv245, err := d.ReadInt()
						if err != nil {
							return err
						}
						v.Tail[i244] = int64(rv245)
					}
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *GenTrailed) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *GenTrailed) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *GenTrailed) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *Inner) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_Inner byte
var qdfFieldHdrs_Inner = [][]byte{qdfFieldHdr_x_197, qdfFieldHdr_y_198}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *Inner) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_Inner, qdfFieldHdrs_Inner)
	e.WriteInt(int64(v.X))
	e.WriteFloat64(float64(v.Y))
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *Inner) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *Inner) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "x":
		{
			rv246, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.X = int(rv246)
		}
	case "y":
		{
			rv247, err := d.ReadFloat64()
			if err != nil {
				return err
			}
			v.Y = rv247
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *Inner) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *Inner) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *Inner) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}

// MarshalQDF appends a qdf-encoded representation of v to dst and returns
// the extended slice.
func (v *Sample) MarshalQDF(dst []byte) ([]byte, error) {
	hadHeader := len(dst) >= 5 && dst[0] == qdf.Magic0 && dst[1] == qdf.Magic1 && dst[2] == qdf.Magic2
	e := qdf.NewEncoderOnBuf(dst, qdf.Fast)
	if hadHeader {
		e.MarkHeaderWritten()
	} else {
		e.EnsureHeader()
	}
	if err := v.EncodeQDF(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

var qdfShapeTok_Sample byte
var qdfFieldHdrs_Sample = [][]byte{qdfFieldHdr_name_92, qdfFieldHdr_age_248, qdfFieldHdr_active_249, qdfFieldHdr_score_250, qdfFieldHdr_tags_186, qdfFieldHdr_meta_251, qdfFieldHdr_inner_185, qdfFieldHdr_when_252, qdfFieldHdr_buf_253, qdfFieldHdr_opt_254, qdfFieldHdr_counts_255}

// EncodeQDF writes v's fields into e. It lets a parent thread one encoder
// through nested values instead of allocating an encoder per value.
func (v *Sample) EncodeQDF(e *qdf.Encoder) error {
	e.StructShape(&qdfShapeTok_Sample, qdfFieldHdrs_Sample)
	e.WriteString(string(v.Name))
	e.WriteInt(int64(v.Age))
	e.WriteBool(bool(v.Active))
	e.WriteFloat64(float64(v.Score))
	if v.Tags == nil {
		e.WriteNil()
	} else {
		e.WriteArrayHeader(len(v.Tags))
		for i256 := range v.Tags {
			e.WriteString(string(v.Tags[i256]))
		}
	}
	if v.Meta == nil {
		e.WriteNil()
	} else {
		e.WriteMapHeader(len(v.Meta))
		if e.Canonical() {
			ks259 := make([]string, 0, len(v.Meta))
			for k257 := range v.Meta {
				ks259 = append(ks259, k257)
			}
			slices.Sort(ks259)
			for _, k257 := range ks259 {
				vv258 := v.Meta[k257]
				e.WriteString(string(k257))
				e.WriteString(string(vv258))
			}
		} else {
			for k257, vv258 := range v.Meta {
				e.WriteString(string(k257))
				e.WriteString(string(vv258))
			}
		}
	}
	if err := qdf.EncodeNested(e, &v.Inner); err != nil {
		return err
	}
	{
		_t := (v.When).UTC()
		e.WriteTimestamp(_t.Unix(), uint32(_t.Nanosecond()))
	}
	if v.Buf == nil {
		e.WriteNil()
	} else {
		e.WriteBytes([]byte(v.Buf))
	}
	if v.OptPtr == nil {
		e.WriteNil()
	} else {
		if err := qdf.EncodeNested(e, v.OptPtr); err != nil {
			return err
		}
	}
	e.WriteArrayHeader(3)
	for i260 := range v.Counts {
		e.WriteInt(int64(v.Counts[i260]))
	}
	return nil
}

// DecodeQDF reads v's fields from the shared decoder d, advancing it. It lets
// a parent thread one decoder through nested values (see qdf.DecodeNested).
func (v *Sample) DecodeQDF(d *qdf.Decoder) error {
	names, plainN, shaped, err := d.ReadStructHeader()
	if err != nil {
		return err
	}
	if shaped {
		for _, name := range names {
			if err := v.decodeQDFField(d, name); err != nil {
				return err
			}
		}
		return nil
	}
	for range plainN {
		kb, err := d.ReadStringBytes()
		if err != nil {
			return err
		}
		if err := v.decodeQDFField(d, string(kb)); err != nil {
			return err
		}
	}
	return nil
}

func (v *Sample) decodeQDFField(d *qdf.Decoder, name string) error {
	switch name {
	case "name":
		{
			rv261, err := d.ReadString()
			if err != nil {
				return err
			}
			v.Name = rv261
		}
	case "age":
		{
			rv262, err := d.ReadInt()
			if err != nil {
				return err
			}
			v.Age = int(rv262)
		}
	case "active":
		{
			rv263, err := d.ReadBool()
			if err != nil {
				return err
			}
			v.Active = rv263
		}
	case "score":
		{
			rv264, err := d.ReadFloat64()
			if err != nil {
				return err
			}
			v.Score = rv264
		}
	case "tags":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Tags = nil
			} else {
				n265, err := d.ReadArrayHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n265, 1); err != nil {
					return err
				}
				v.Tags = make([]string, n265)
				for i266 := range n265 {
					{
						rv267, err := d.ReadString()
						if err != nil {
							return err
						}
						v.Tags[i266] = rv267
					}
				}
			}
		}
	case "meta":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Meta = nil
			} else {
				n268, err := d.ReadMapHeader()
				if err != nil {
					return err
				}
				if err := d.CheckLength(n268, 1); err != nil {
					return err
				}
				v.Meta = make(map[string]string, n268)
				for range n268 {
					var k269 string
					var vv270 string
					kb271, err := d.ReadStringBytes()
					if err != nil {
						return err
					}
					k269 = string(d.InternKey(kb271))
					{
						rv272, err := d.ReadString()
						if err != nil {
							return err
						}
						vv270 = rv272
					}
					v.Meta[k269] = vv270
				}
			}
		}
	case "inner":
		if err := qdf.DecodeNested(d, &v.Inner); err != nil {
			return err
		}
	case "when":
		{
			sec273, nsec274, err := d.ReadTimestamp()
			if err != nil {
				return err
			}
			v.When = time.Unix(sec273, int64(nsec274)).UTC()
		}
	case "buf":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.Buf = nil
			} else {
				_v, err := d.ReadBytes()
				if err != nil {
					return err
				}
				v.Buf = _v
			}
		}
	case "opt":
		{
			isNil, err := d.IsNil()
			if err != nil {
				return err
			}
			if isNil {
				v.OptPtr = nil
			} else {
				v.OptPtr = new(Inner)
				if err := qdf.DecodeNested(d, v.OptPtr); err != nil {
					return err
				}
			}
		}
	case "counts":
		{
			n275, err := d.ReadArrayHeader()
			if err != nil {
				return err
			}
			if n275 != 3 {
				return qdf.ErrTypeMismatch
			}
			for i276 := range 3 {
				{
					rv277, err := d.ReadInt()
					if err != nil {
						return err
					}
					v.Counts[i276] = int32(rv277)
				}
			}
		}
	default:
		if err := d.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalQDF decodes a qdf payload into v and returns the number of
// bytes consumed.
func (v *Sample) UnmarshalQDF(src []byte) (int, error) {
	return v.UnmarshalQDFArena(src, false, nil)
}

// UnmarshalQDFOpts decodes like UnmarshalQDF; when noCopy is true the decoded
// string and []byte fields alias src instead of copying. The aliases are valid
// only while src stays alive and is not modified (see qdf.WithNoCopy).
func (v *Sample) UnmarshalQDFOpts(src []byte, noCopy bool) (int, error) {
	return v.UnmarshalQDFArena(src, noCopy, nil)
}

// UnmarshalQDFArena decodes like UnmarshalQDFOpts; when a is non-nil the copied
// string fields are packed into the arena instead of one allocation each (see
// qdf.WithArena). The decoded strings then alias the arena's memory.
func (v *Sample) UnmarshalQDFArena(src []byte, noCopy bool, a *qdf.Arena) (int, error) {
	d := qdf.NewDecoderOnBuf(src)
	if noCopy {
		d.SetNoCopy(true)
	}
	if a != nil {
		d.SetArena(a)
	}
	hasHeader := len(src) >= 5 && src[0] == qdf.Magic0 && src[1] == qdf.Magic1 && src[2] == qdf.Magic2
	if !hasHeader {
		d.MarkHeaderRead()
	}
	if err := v.DecodeQDF(d); err != nil {
		return 0, err
	}
	return d.Pos(), nil
}
